https://www.kaggle.com/datasets/rtatman/questionanswer-dataset/data?select=S08_question_answer_pairs.txt

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('data/text-data/S08_question_answer_pairs.txt',sep='\t')
df1

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,yes,easy,easy,S08_set3_a4
1,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,Yes.,easy,easy,S08_set3_a4
2,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,yes,easy,medium,S08_set3_a4
3,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,Yes.,easy,easy,S08_set3_a4
4,Abraham_Lincoln,Did his mother die of pneumonia?,no,easy,medium,S08_set3_a4
...,...,...,...,...,...,...
1710,Woodrow_Wilson,Was Wilson president of the American Political...,Yes,NaN,easy,S08_set3_a8
1711,Woodrow_Wilson,Did he not cast his ballot for John M. Palmer ...,Yes,NaN,easy,S08_set3_a8
1712,Woodrow_Wilson,Did Wilson not spend 1914 through the beginnin...,Yes,NaN,easy,S08_set3_a8
1713,Woodrow_Wilson,"Was Wilson , a staunch opponent of antisemitis...",Yes,NaN,easy,S08_set3_a8
1714,Woodrow_Wilson,What happened in 1917?,"raised billions through Liberty loans, imposed...",NaN,medium,S08_set3_a8

In [3]:
df2 = pd.read_csv('data/text-data/S09_question_answer_pairs.txt',sep='\t')
df2

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
1,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
2,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
3,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
4,Alessandro_Volta,Did Volta have a passion for the study of elec...,yes,easy,medium,S09_set4_a10
...,...,...,...,...,...,...
820,Xylophone,What is the earliest historical reference in E...,Arnold Schlick's Spiegel der Orgelmacher und O...,medium,medium,S09_set2_a8
821,Xylophone,How are western-style xylophones characterised?,"by a bright, sharp tone and high register",medium,medium,S09_set2_a8
822,Xylophone,Can a xylophone be 3 octaves?,yes,hard,hard,S09_set2_a8
823,Xylophone,Can a short bar follow a long bar?,no,hard,hard,S09_set2_a8
824,Xylophone,Did vibraphones exist in 1930?,yes,hard,hard,S09_set2_a8

In [4]:
df3 = pd.read_csv('data/text-data/S10_question_answer_pairs.txt',sep='\t',encoding='latin-1')
df3

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,Alessandro Volta was not a professor of chemis...,easy,easy,S10_set4_a10
1,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,No,easy,hard,S10_set4_a10
2,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...,easy,easy,S10_set4_a10
3,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Yes,easy,easy,S10_set4_a10
4,Alessandro_Volta,Was Alessandro Volta taught in public schools?,Volta was taught in public schools.,easy,easy,S10_set4_a10
...,...,...,...,...,...,...
1453,Zebra,What areas do the Grevy's Zebras inhabit?,NaN,hard,NaN,S10_set1_a9
1454,Zebra,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur...",hard,medium,S10_set1_a9
1455,Zebra,Which species of zebra is known as the common ...,Plains Zebra,hard,medium,S10_set1_a9
1456,Zebra,At what age can a zebra breed?,five or six,hard,medium,S10_set1_a9
1457,Zebra,At what age can a zebra breed?,5 or 6,hard,hard,S10_set1_a9

In [5]:
df1.shape,df2.shape,df3.shape

((1715, 6), (825, 6), (1458, 6))

In [6]:
1715 + 825 + 1458

3998

In [7]:
df = pd.concat(
    [df1,df2,df3],axis=0
)[['Question','Answer']]

In [8]:
df

,Question,Answer
0,Was Abraham Lincoln the sixteenth President of...,yes
1,Was Abraham Lincoln the sixteenth President of...,Yes.
2,Did Lincoln sign the National Banking Act of 1...,yes
3,Did Lincoln sign the National Banking Act of 1...,Yes.
4,Did his mother die of pneumonia?,no
...,...,...
1453,What areas do the Grevy's Zebras inhabit?,NaN
1454,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur..."
1455,Which species of zebra is known as the common ...,Plains Zebra
1456,At what age can a zebra breed?,five or six
1457,At what age can a zebra breed?,5 or 6

In [9]:
sum(df['Answer'].value_counts().head(6).values)

np.int64(1367)

In [10]:
# words_to_remove = ['Yes', 'yes', 'Yes.', 'No', 'no', 'No.']
# df['Answer'] = df['Answer'].replace(words_to_remove, np.nan)

In [11]:
df.isnull().sum()

Question     37
Answer      578
dtype: int64

In [12]:
df = df.dropna(axis=0)

In [13]:
df.shape

(3420, 2)

In [14]:
df = df.sample(150).reset_index(drop=True)

In [15]:
df

,Question,Answer
0,What language besides Malay is in the Austrone...,Malagasy
1,What percentage of Liechtenstein's population ...,67%
2,What is the cause of local earthquakes?,It was the San Andreas Fault which slipped and...
3,Sea otters eat what?,Shellfish and other invertebrates
4,Was Calvin Coolidge Republican?,Yes
...,...,...
145,Has Urbanization eliminated many areas of form...,Yes
146,Is Vietnamese the mother tongue of the Vietnam...,Yes
147,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...
148,Is Swahili a Bantu language?,yes
149,Are there many Roma in Romania?,No.

In [16]:
import re

In [17]:
def tokenize(text):
    if isinstance(text, str): 
        text = text.lower()
        
        # We added \d to the brackets to catch all numbers
        # Alternatively, you could write 0-9 inside the brackets
        text = re.sub(r'[!-@#$%^&*()_+><:;?\'\d]', '', text)
        
        return text.split()
    return text

In [18]:
tokenize(df['Question'][0])

['what',
 'language',
 'besides',
 'malay',
 'is',
 'in',
 'the',
 'austronesia',
 'language',
 'family']

In [19]:
# Vocab (for unknow words)

vocab = {'<UNK>':0}

In [20]:
def build_vocab(row):
    # if pd.isna(row['Question']) or pd.isna(row['Answer']):
    #     return

    tokenized_question = tokenize(row['Question'])
    tokenized_answer = tokenize(row['Answer'])

    for token in tokenized_question + tokenized_answer:
        if token not in vocab:
            vocab[token] = len(vocab)

In [21]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
145    None
146    None
147    None
148    None
149    None
Length: 150, dtype: object

In [22]:
len(vocab)

789

In [23]:
vocab

{'<UNK>': 0,
 'what': 1,
 'language': 2,
 'besides': 3,
 'malay': 4,
 'is': 5,
 'in': 6,
 'the': 7,
 'austronesia': 8,
 'family': 9,
 'malagasy': 10,
 'percentage': 11,
 'of': 12,
 'liechtensteins': 13,
 'population': 14,
 'foreignborn': 15,
 'cause': 16,
 'local': 17,
 'earthquakes': 18,
 'it': 19,
 'was': 20,
 'san': 21,
 'andreas': 22,
 'fault': 23,
 'which': 24,
 'slipped': 25,
 'and': 26,
 'caused': 27,
 'sea': 28,
 'otters': 29,
 'eat': 30,
 'shellfish': 31,
 'other': 32,
 'invertebrates': 33,
 'calvin': 34,
 'coolidge': 35,
 'republican': 36,
 'yes': 37,
 'canada': 38,
 'bilingual': 39,
 'prompted': 40,
 'city': 41,
 'to': 42,
 'upgrade': 43,
 'its': 44,
 'building': 45,
 'codes': 46,
 'threat': 47,
 'major': 48,
 'are': 49,
 'cougars': 50,
 'larger': 51,
 'than': 52,
 'jaguars': 53,
 'no': 54,
 'how': 55,
 'long': 56,
 'an': 57,
 'adult': 58,
 'paw': 59,
 'print': 60,
 'approximately': 61,
 'cm': 62,
 'inches': 63,
 'when': 64,
 'did': 65,
 'a': 66,
 'standard': 67,
 'common': 68,
 'become': 69,
 'available': 70,
 'all': 71,
 'swedes': 72,
 'th': 73,
 'century': 74,
 'do': 75,
 'giraffes': 76,
 'give': 77,
 'birth': 78,
 'standing': 79,
 'up': 80,
 'there': 81,
 'way': 82,
 'approximate': 83,
 'age': 84,
 'turtle': 85,
 'many': 86,
 'james': 87,
 'watts': 88,
 'children': 89,
 'not': 90,
 'live': 91,
 'adulthood': 92,
 'album': 93,
 'song': 94,
 'bonny': 95,
 'swans': 96,
 'from': 97,
 'mask': 98,
 'mirror': 99,
 'greek': 100,
 'mythical': 101,
 'creatures': 102,
 'were': 103,
 'depicted': 104,
 'holding': 105,
 'cymbals': 106,
 'fauns': 107,
 'satyrs': 108,
 'penguins': 109,
 'considered': 110,
 'higher': 111,
 'waterbirds': 112,
 'tesla': 113,
 'win': 114,
 'nobel': 115,
 'prize': 116,
 'where': 117,
 'watt': 118,
 'memorial': 119,
 'college': 120,
 'greenock': 121,
 'london': 122,
 'capital': 123,
 'united': 124,
 'kingdom': 125,
 'legs': 126,
 'lobsters': 127,
 'have': 128,
 'ulysses': 129,
 'battle': 130,
 'champion': 131,
 'hill': 132,
 'used': 133,
 'tune': 134,
 'cello': 135,
 'pegs': 136,
 'theodore': 137,
 'roosevelt': 138,
 'gramercy': 139,
 'section': 140,
 'new': 141,
 'york': 142,
 'why': 143,
 'giant': 144,
 'otter': 145,
 'becoming': 146,
 'increasingly': 147,
 'rare': 148,
 'poaching': 149,
 'habitat': 150,
 'loss': 151,
 'use': 152,
 'mercury': 153,
 'illegal': 154,
 'alluvial': 155,
 'gold': 156,
 'mining': 157,
 'elephants': 158,
 'communicate': 159,
 'over': 160,
 'distances': 161,
 'by': 162,
 'producing': 163,
 'receiving': 164,
 'low': 165,
 'frequency': 166,
 'sound': 167,
 'melbourne': 168,
 'home': 169,
 'australias': 170,
 'busiest': 171,
 'seaport': 172,
 'park': 173,
 'reserve': 174,
 'located': 175,
 'near': 176,
 'downtown': 177,
 'area': 178,
 'geographically': 179,
 'vast': 180,
 'ethnically': 181,
 'diverse': 182,
 'country': 183,
 'does': 184,
 'piano': 185,
 'fewer': 186,
 'strings': 187,
 'harp': 188,
 'monroe': 189,
 'graduate': 190,
 'william': 191,
 'mary': 192,
 'avogadros': 193,
 'number': 194,
 'x': 195,
 'central': 196,
 'adjacent': 197,
 'uhuru': 198,
 'black': 199,
 'moth': 200,
 'mean': 201,
 'that': 202,
 'someone': 203,
 'has': 204,
 'died': 205,
 'philippines': 206,
 'butterfly': 207,
 'or': 208,
 'he': 209,
 'regarded': 210,
 'as': 211,
 'mostly': 212,
 'reclusive': 213,
 'artist': 214,
 'deepest': 215,
 'note': 216,
 'classical': 217,
 'lyre': 218,
 'relation': 219,
 'players': 220,
 'body': 221,
 'farthest': 222,
 'flamenco': 223,
 'guitar': 224,
 'similar': 225,
 'who': 226,
 'became': 227,
 'adversaries': 228,
 'with': 229,
 'nikola': 230,
 'edison': 231,
 'mayor': 232,
 'ottawa': 233,
 'larry': 234,
 'obrien': 235,
 'celebrator': 236,
 'beauty': 237,
 'especially': 238,
 'feminine': 239,
 'sensuality': 240,
 'been': 241,
 'said': 242,
 '``renoir': 243,
 'final': 244,
 'representative': 245,
 'tradition': 246,
 'runs': 247,
 'directly': 248,
 'rubens': 249,
 'watteau': 250,
 'variations': 251,
 'formal': 252,
 'written': 253,
 'version': 254,
 'quite': 255,
 'limited': 256,
 'being': 257,
 'restricted': 258,
 'largely': 259,
 'spelling': 260,
 'differences': 261,
 'between': 262,
 'british': 263,
 'american': 264,
 'english': 265,
 'jakarta': 266,
 'punishment': 267,
 'for': 268,
 'firstdegree': 269,
 'murder': 270,
 'laws': 271,
 'allow': 272,
 'singapore': 273,
 'drug': 274,
 'trafficking': 275,
 'almost': 276,
 'exclusively': 277,
 'southern': 278,
 'hemisphere': 279,
 'leopards': 280,
 'tail': 281,
 'wolves': 282,
 'howl': 283,
 'howling': 284,
 'helps': 285,
 'pack': 286,
 'members': 287,
 'keep': 288,
 'touch': 289,
 'allowing': 290,
 'them': 291,
 'effectively': 292,
 'thickly': 293,
 'forested': 294,
 'areas': 295,
 'great': 296,
 'also': 297,
 'call': 298,
 'specific': 299,
 'location': 300,
 'can': 301,
 'serve': 302,
 'declaration': 303,
 'territory': 304,
 'shown': 305,
 'dominant': 306,
 'wolfaposs': 307,
 'tendency': 308,
 'respond': 309,
 'human': 310,
 'imitation': 311,
 'rival': 312,
 'wolf': 313,
 'considers': 314,
 'own': 315,
 'both': 316,
 'sexes': 317,
 'giraffe': 318,
 'horns': 319,
 'according': 320,
 'readers': 321,
 'digest': 322,
 'finland': 323,
 'best': 324,
 'living': 325,
 'discovered': 326,
 'about': 327,
 'turtles': 328,
 'organs': 329,
 'they': 330,
 'break': 331,
 'down': 332,
 'gray': 333,
 'native': 334,
 'north': 335,
 'america': 336,
 'cellos': 337,
 'constructed': 338,
 'glue': 339,
 'berlin': 340,
 'architect': 341,
 'norman': 342,
 'foster': 343,
 'remodel': 344,
 's': 345,
 'reichstag': 346,
 'nickname': 347,
 'roosevelts': 348,
 'sister': 349,
 'anna': 350,
 'bamie': 351,
 'official': 352,
 'transnational': 353,
 'bridge': 354,
 'completed': 355,
 'oresund': 356,
 'spoken': 357,
 'dialect': 358,
 'ethnic': 359,
 'malays': 360,
 'uruguays': 361,
 'oldest': 362,
 'church': 363,
 'carlos': 364,
 'maldonado': 365,
 'modern': 366,
 'metal': 367,
 'polymers': 368,
 'animal': 369,
 'plant': 370,
 'product': 371,
 'materials': 372,
 'another': 373,
 'primary': 374,
 'objective': 375,
 'fillmore': 376,
 'preserve': 377,
 'union': 378,
 'intensifying': 379,
 'slavery': 380,
 'debate': 381,
 'suicidebombing': 382,
 'kill': 383,
 'teacher': 384,
 'doha': 385,
 'theatre': 386,
 'border': 387,
 'norway': 388,
 'event': 389,
 'marked': 390,
 'end': 391,
 'old': 392,
 'portuguese': 393,
 'period': 394,
 'publication': 395,
 'cancioneiro': 396,
 'geral': 397,
 'garcia': 398,
 'de': 399,
 'resende': 400,
 'south': 401,
 'china': 402,
 'linguistically': 403,
 'different': 404,
 'displays': 405,
 'more': 406,
 'linguistic': 407,
 'diversity': 408,
 'his': 409,
 'father': 410,
 'member': 411,
 'sandemanian': 412,
 'sect': 413,
 'matti': 414,
 'vanhanen': 415,
 'prime': 416,
 'minister': 417,
 'wilsons': 418,
 'slaves': 419,
 'carried': 420,
 'tacit': 421,
 'recognition': 422,
 'qatars': 423,
 'status': 424,
 'distinct': 425,
 'bahrain': 426,
 'protectorate': 427,
 'per': 428,
 'colonel': 429,
 'lewis': 430,
 'pelly': 431,
 'asking': 432,
 'negotiate': 433,
 'qatar': 434,
 'after': 435,
 'bahrains': 436,
 'violation': 437,
 'anglobahraini': 438,
 'treaty': 439,
 'one': 440,
 'most': 441,
 'widely': 442,
 'languages': 443,
 'world': 444,
 'achieved': 445,
 'international': 446,
 'fame': 447,
 'leading': 448,
 'general': 449,
 'civil': 450,
 'war': 451,
 'grant': 452,
 'volta': 453,
 'made': 454,
 'count': 455,
 'napoleon': 456,
 'john': 457,
 'adams': 458,
 'get': 459,
 'along': 460,
 'alexander': 461,
 'hamilton': 462,
 'determined': 463,
 'pursue': 464,
 'mathematics': 465,
 'charlesaugustin': 466,
 'coulomb': 467,
 'defeated': 468,
 'reelection': 469,
 'the``': 470,
 'revolution': 471,
 'thomas': 472,
 'jefferson': 473,
 'breeze': 474,
 'eazy': 475,
 'method': 476,
 'sometimes': 477,
 'teach': 478,
 'younger': 479,
 'students': 480,
 'mother': 481,
 'die': 482,
 'pneumonia': 483,
 'suborders': 484,
 'divided': 485,
 'into': 486,
 'three': 487,
 'korean': 488,
 'descended': 489,
 'middle': 490,
 'county': 491,
 'lincoln': 492,
 'born': 493,
 'southeast': 494,
 'hardin': 495,
 'kentucky': 496,
 'national': 497,
 'currency': 498,
 'liechtenstein': 499,
 'swiss': 500,
 'franc': 501,
 'densely': 502,
 'populated': 503,
 'part': 504,
 'quebec': 505,
 'citywindsor': 506,
 'corridor': 507,
 'lakes': 508,
 'saint': 509,
 'lawrence': 510,
 'river': 511,
 'pocket': 512,
 'trumpets': 513,
 'compact': 514,
 'b': 515,
 'district': 516,
 'ford': 517,
 'elected': 518,
 'michigans': 519,
 'congressional': 520,
 'eggs': 521,
 'layed': 522,
 'on': 523,
 'land': 524,
 'woodrow': 525,
 'wilson': 526,
 'create': 527,
 'league': 528,
 'nations': 529,
 'drum': 530,
 'percussion': 531,
 'group': 532,
 'french': 533,
 'scottish': 534,
 'important': 535,
 'ciliwung': 536,
 'kuala': 537,
 'lumpur': 538,
 'selangor': 539,
 'state': 540,
 'westernstyle': 541,
 'xylophones': 542,
 'characterised': 543,
 'bright': 544,
 'sharp': 545,
 'tone': 546,
 'high': 547,
 'register': 548,
 'cymbal': 549,
 'bell': 550,
 'center': 551,
 'savings': 552,
 'loans': 553,
 'bank': 554,
 'founded': 555,
 'first': 556,
 'cottonweaving': 557,
 'mill': 558,
 'year': 559,
 'violin': 560,
 'usually': 561,
 'permanently': 562,
 'stationed': 563,
 'paris': 564,
 'skin': 565,
 'tough': 566,
 'kangaroo': 567,
 'marsupial': 568,
 'led': 569,
 'pascal': 570,
 'religious': 571,
 'conversion': 572,
 'sickness': 573,
 'jansenism': 574,
 'parks': 575,
 'francisco': 576,
 'only': 577,
 'managed': 578,
 'california': 579,
 'system': 580,
 'candlestick': 581,
 'point': 582,
 'earliest': 583,
 'historical': 584,
 'reference': 585,
 'europe': 586,
 'arnold': 587,
 'schlicks': 588,
 'spiegel': 589,
 'der': 590,
 'orgelmacher': 591,
 'und': 592,
 'organisten': 593,
 'expression': 594,
 'conceptual': 595,
 'framework': 596,
 'testing': 597,
 'computer': 598,
 'systems': 599,
 'quacks': 600,
 'like': 601,
 'duck': 602,
 'henri': 603,
 'becquerel': 604,
 'sole': 605,
 'winner': 606,
 'physics': 607,
 'cities': 608,
 'six': 609,
 'elephant': 610,
 'very': 611,
 'temperature': 612,
 'regulation': 613,
 'ears': 614,
 'romania': 615,
 'share': 616,
 'same': 617,
 'moldova': 618,
 'newton': 619,
 'statue': 620,
 'display': 621,
 'oxford': 622,
 'university': 623,
 'museum': 624,
 'natural': 625,
 'history': 626,
 'german': 627,
 'years': 628,
 'ago': 629,
 'african': 630,
 'people': 631,
 'spread': 632,
 'across': 633,
 'francophone': 634,
 'countries': 635,
 'speak': 636,
 'either': 637,
 'second': 638,
 'president': 639,
 'march': 640,
 'municipalities': 641,
 'within': 642,
 'oberland': 643,
 'species': 644,
 'asian': 645,
 'named': 646,
 'apostle': 647,
 'peter': 648,
 'isaac': 649,
 'sleep': 650,
 'had': 651,
 'smoked': 652,
 'sporadically': 653,
 'abbreviation': 654,
 'violoncello': 655,
 'eels': 656,
 'fresh': 657,
 'water': 658,
 'presidential': 659,
 'hero': 660,
 'koala': 661,
 'fill': 662,
 'ecological': 663,
 'role': 664,
 'sloth': 665,
 'fills': 666,
 'canadian': 667,
 'soldiers': 668,
 'vimy': 669,
 'ridge': 670,
 'singaporeans': 671,
 'enjoy': 672,
 'squid': 673,
 'name': 674,
 'agnus': 675,
 'muirhead': 676,
 'moden': 677,
 'orchestras': 678,
 'lima': 679,
 'celsius': 680,
 'bass': 681,
 'trumpet': 682,
 'smallest': 683,
 'wrote': 684,
 'novel': 685,
 'finnish': 686,
 'published': 687,
 'aleksis': 688,
 'kivi': 689,
 'bartolomeo': 690,
 'cristofori': 691,
 'invent': 692,
 'plymouth': 693,
 'windsor': 694,
 'vermont': 695,
 'arabs': 696,
 'consider': 697,
 'literary': 698,
 'arabic': 699,
 'bad': 700,
 'question': 701,
 'fish': 702,
 'happened': 703,
 'blah': 704,
 'upright': 705,
 'pianos': 706,
 'because': 707,
 'frame': 708,
 'vertical': 709,
 'michael': 710,
 'faraday`s': 711,
 'birthplace': 712,
 'newington': 713,
 'butts': 714,
 'grover': 715,
 'cleveland': 716,
 'sheriff': 717,
 'erie': 718,
 'coulombs': 719,
 'law': 720,
 'definition': 721,
 'electrostatic': 722,
 'force': 723,
 'attraction': 724,
 'repulsion': 725,
 'introduce': 726,
 'bicameral': 727,
 'legislature': 728,
 'argue': 729,
 'perfect': 730,
 'possible': 731,
 'procedure': 732,
 'geometry': 733,
 'ants': 734,
 'belong': 735,
 'hymenoptera': 736,
 'order': 737,
 'battery': 738,
 'credited': 739,
 'be': 740,
 'cell': 741,
 'polar': 742,
 'bears': 743,
 'diseases': 744,
 'mites': 745,
 'parasites': 746,
 'variety': 747,
 'well': 748,
 'small': 749,
 'mammals': 750,
 'birds': 751,
 'unrelated': 752,
 'ducks': 753,
 'confused': 754,
 'loons': 755,
 'divers': 756,
 'grebes': 757,
 'gallinules': 758,
 'coots': 759,
 'vitula': 760,
 'stringed': 761,
 'instrument': 762,
 'shaped': 763,
 'hourglass': 764,
 'graduating': 765,
 'amherst': 766,
 'moved': 767,
 'northampton': 768,
 'massachussetts': 769,
 'leopard': 770,
 'mammal': 771,
 'urbanization': 772,
 'eliminated': 773,
 'former': 774,
 'rainforest': 775,
 'remaining': 776,
 'bukit': 777,
 'timah': 778,
 'nature': 779,
 'vietnamese': 780,
 'tongue': 781,
 'alessandro': 782,
 'remotely': 783,
 'operated': 784,
 'pistol': 785,
 'swahili': 786,
 'bantu': 787,
 'roma': 788}

In [24]:
def text_to_indices(text, vocab):

    return [
        vocab.get(token, vocab['<UNK>'])
        for token in tokenize(text)
    ]

In [25]:
df['Question'][0].split()

['What',
 'language',
 'besides',
 'Malay',
 'is',
 'in',
 'the',
 'Austronesia',
 'language',
 'family?']

In [26]:
text_to_indices(df['Question'][0],vocab)

[1, 2, 3, 4, 5, 6, 7, 8, 2, 9]

In [27]:
df

,Question,Answer
0,What language besides Malay is in the Austrone...,Malagasy
1,What percentage of Liechtenstein's population ...,67%
2,What is the cause of local earthquakes?,It was the San Andreas Fault which slipped and...
3,Sea otters eat what?,Shellfish and other invertebrates
4,Was Calvin Coolidge Republican?,Yes
...,...,...
145,Has Urbanization eliminated many areas of form...,Yes
146,Is Vietnamese the mother tongue of the Vietnam...,Yes
147,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...
148,Is Swahili a Bantu language?,yes
149,Are there many Roma in Romania?,No.

In [28]:
df.iloc[0]['Question']

'What language besides Malay is in the Austronesia language family?'

In [29]:
import torch
from torch.utils.data import DataLoader , Dataset

In [30]:
class QADataset(Dataset):

    def __init__(self,df,vocab):
        self.df = df
        self.vocab = vocab

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self,index):

        numerical_question = text_to_indices(self.df.iloc[index]['Question'],self.vocab)
        numerical_answer = text_to_indices(self.df.iloc[index]['Answer'],self.vocab)

        return torch.tensor(numerical_question) , torch.tensor(numerical_answer)

In [31]:
dataset = QADataset(df,vocab)

In [32]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [33]:
for question , answer in dataloader:
    print(question,answer[0])

tensor([[  7, 552,  26, 553, 554,  20, 555, 211,  20,   7, 556, 557, 558,   6,
           1, 559]]) tensor([])
tensor([[ 75, 671, 672, 673]]) tensor([37])
tensor([[  1, 100, 101, 102, 103, 104, 105, 106]]) tensor([107,  26, 108])
tensor([[  1,  20,   7, 674,  12,  87,  88, 481]]) tensor([675, 676])
tensor([[  1,  65, 570, 729,  20, 211, 730, 211, 731]]) tensor([  7, 732, 133,   6, 733])
tensor([[  1,  65,  35,  75, 435, 765,  97, 766]]) tensor([ 35, 767,  42, 768, 769])
tensor([[  5,  87, 118, 533]]) tensor([ 54, 209,  20, 534])
tensor([[117,   5,   7,  87, 118, 119, 120]]) tensor([  7,  87, 118, 119,   5,   6, 121])
tensor([[117,  65,  66, 382, 383,  66, 384,   6]]) tensor([385, 220, 386])
tensor([[55, 56,  5, 57, 58, 50, 59, 60]]) tensor([57, 58, 50, 59, 60,  5, 61, 62, 63, 56])
tensor([[ 20, 453, 454,  66, 455, 162, 456,   6]]) tensor([ 37, 453,  20, 454,  66, 455, 162, 456,   6])
tensor([[  5, 266,  66,  41]]) tensor([37])
tensor([[204, 772, 773,  86, 295,  12, 774, 374, 775, 229,   7, 577, 776, 178,
          12, 374, 775, 257, 777, 778, 779, 174]]) tensor([37])
tensor([[ 65, 457, 458, 459, 460, 229, 461, 462]]) tensor([54])
tensor([[226, 445, 446, 447, 211,   7, 448, 378, 449,   6,   7, 264, 450, 451]]) tensor([452])
tensor([[  1, 184, 760, 201]]) tensor([761, 762])
tensor([[ 65, 418, 410, 315, 419]]) tensor([37])
tensor([[ 65, 667, 668, 114,   7, 130,  12, 669, 670,   6]]) tensor([54, 19, 65, 90])
tensor([[ 20, 373, 374, 375,  12, 376,  42, 377,   7, 378,  97,   7, 379, 380,
         381]]) tensor([37])
tensor([[ 65, 409, 481, 482,  12, 483]]) tensor([54])
tensor([[ 55,  86, 349, 608, 184,   7,  41,  12, 168, 128]]) tensor([609])
tensor([[  1, 569, 570,  42, 409, 571, 572]]) tensor([573,  26, 574])
tensor([[226, 227, 228, 229, 230, 113]]) tensor([231])
tensor([[184, 615, 616,   7, 617,   2, 229, 618]]) tensor([37])
tensor([[ 64,  20, 466, 399, 467, 562, 563,   6, 564]]) tensor([466, 399, 467,  20, 562, 563,   6, 564,   6])
tensor([[ 24, 491,  20, 492, 493,   6]]) tensor([494, 495, 491, 496])
tensor([[  1, 516,  20, 517, 518,  97]]) tensor([519,  73, 520, 516])
tensor([[117,   5,   7, 173,  12,   7, 174, 175]]) tensor([176,   7, 177, 178])
tensor([[  5,   7, 624,  12, 156,   6, 679]]) tensor([37])
tensor([[ 55,   5, 401, 402, 403, 404,  97, 335, 402]]) tensor([401, 402, 405, 406, 407, 408])
tensor([[  1,   5,  16,  12, 742, 743, 565, 744]]) tensor([745, 208,  32, 746])
tensor([[  1,   5, 719, 720]]) tensor([  7, 721,  12,   7, 722, 723,  12, 724,  26, 725])
tensor([[ 65, 113, 114,   7, 115, 116]]) tensor([54])
tensor([[  1, 353, 354,  20, 355,   6]]) tensor([356, 354])
tensor([[24, 93, 20,  7, 94,  7, 95, 96, 97]]) tensor([ 7, 98, 26, 99])
tensor([[143,  49, 705, 706, 406, 514]]) tensor([705, 706,  49, 406, 514, 707,   7, 708,  26, 187,  49, 709])
tensor([[64, 65, 66, 67, 26, 68,  2, 69, 70, 42, 71, 72]]) tensor([ 6,  7, 73, 74])
tensor([[320,  42, 321, 322,   5, 323, 324, 268, 325]]) tensor([37])
tensor([[117,   5,   7, 441, 502, 503, 504,  12,  38]]) tensor([  7, 441, 502, 503, 504,  12,   7, 183,   5,   7, 505, 506, 507, 460,
          7, 296, 508,  26, 509, 510, 511,   6,   7, 494])
tensor([[143,   5,   7, 144, 145, 146, 147, 148]]) tensor([149, 150, 151,  26,   7, 152,  12, 153,   6, 154, 155, 156, 157])
tensor([[ 55,  86, 325, 644,  12, 645, 158,  49,  81]]) tensor([440])
tensor([[226, 463,  42, 464, 465]]) tensor([466, 399, 467])
tensor([[55, 86, 12, 87, 88, 89, 65, 90, 91, 42, 92]]) tensor([])
tensor([[184,  19, 128,  66, 387, 229, 388]]) tensor([37])
tensor([[117,   5,  81,  66, 619, 620, 523, 621]]) tensor([622, 623, 624,  12, 625, 626])
tensor([[  1, 504,  12,  57, 610,   5, 611, 535, 268, 612, 613]]) tensor([614])
tensor([[184,  66,  67, 185, 128, 186, 187,  52,  66, 188]]) tensor([54])
tensor([[ 65, 782, 453, 692,   7, 783, 784, 785]]) tensor([782, 453,  65, 692,   7, 783, 784, 785])
tensor([[117,  20,   7, 215, 216,  12,   7, 217, 218,   6, 219,  42,   7, 220,
         221]]) tensor([ 19,  20, 222,  97,   7, 220, 221])
tensor([[  1,   5, 193, 194]]) tensor([195])
tensor([[ 20,  34,  35, 493,   6, 693, 694, 491, 695]]) tensor([37])
tensor([[  5,   4, 357, 211,  17, 358,  12, 359, 360]]) tensor([37])
tensor([[ 55,  86, 187, 184,  66, 560, 561, 128]]) tensor([])
tensor([[ 55,  86, 540, 575,  49,   6,  21, 576]]) tensor([ 81,   5, 577, 440, 173, 578, 162,   7, 579, 540, 173, 580, 581, 582])
tensor([[117,   5, 361, 362, 363]]) tensor([ 21, 364, 365])
tensor([[28, 29, 30,  1]]) tensor([31, 26, 32, 33])
tensor([[ 49, 337, 338, 229, 339]]) tensor([37])
tensor([[  5,   4,   7, 440,  12,   7, 441, 442, 357, 443,   6,   7, 444]]) tensor([37])
tensor([[226, 684,   7, 556, 685,   6, 686]]) tensor([  7, 556, 685,   6, 686,  20, 687, 162, 688, 689])
tensor([[  5,   7, 530,  66, 411,  12,   7, 531, 532]]) tensor([37])
tensor([[ 20, 129, 452,  66, 449,   6,   7, 264, 450, 451]]) tensor([37])
tensor([[  1,  20,   7, 347,  12, 137, 348, 349, 350]]) tensor([351])
tensor([[49, 50, 51, 52, 53]]) tensor([54])
tensor([[  1, 752, 658, 751,  49, 753, 477, 754, 229]]) tensor([755, 208, 756, 757, 758,  26, 759])
tensor([[  5, 122,   7, 123,  12,   7, 124, 125]]) tensor([37])
tensor([[  1, 594,   5, 504,  12,  66, 595, 596, 268, 597, 598, 599]]) tensor([600, 601,  66, 602])
tensor([[ 49,  17, 251,   6,   7, 252, 253, 254,  12,   7,   2, 255, 256, 257,
         258, 259,  42,   7, 260, 261, 262, 263,  26, 264, 265]]) tensor([37])
tensor([[ 49,  81,  86, 788,   6, 615]]) tensor([54])
tensor([[211,  66, 236,  12, 237,  26, 238, 239, 240, 204,  19, 241, 242, 202,
         243,   5,   7, 244, 245,  12,  66, 246,  24, 247, 248,  97, 249,  42,
         250]]) tensor([37])
tensor([[ 55,  86, 484,  49, 328, 485, 486]]) tensor([487])
tensor([[ 1, 11, 12, 13, 14,  5, 15]]) tensor([])
tensor([[ 20, 603, 604,   7, 605, 606,  12,   7, 115, 116,   6, 607]]) tensor([54])
tensor([[143,  75, 282, 283]]) tensor([284, 285, 286, 287, 288,   6, 289, 290, 291,  42, 159, 292,   6, 293,
        294, 295, 208, 160, 296, 161, 284, 297, 285,  42, 298, 286, 287,  42,
         66, 299, 300, 284, 301, 297, 302, 211,  66, 303,  12, 304, 211, 305,
          6,  66, 306, 307, 308,  42, 309,  42,  66, 310, 311,  12,  66, 312,
        313,   6,  57, 178,   7, 313, 314,  44, 315])
tensor([[  1, 204, 241, 326, 327, 328, 329]]) tensor([330,  75,  90, 331, 332])
tensor([[  5,   7, 560, 763, 601,  57, 764]]) tensor([37])
tensor([[  5,   7, 441, 535, 511,   7, 536, 511]]) tensor([37])
tensor([[ 75, 109,  91, 276, 277,   6,   7, 278, 279]]) tensor([37])
tensor([[  5,   7, 474, 475, 476, 477, 133,  42, 478, 479, 480]]) tensor([37])
tensor([[ 65, 525, 526, 527,   7, 528,  12, 529]]) tensor([37])
tensor([[  5, 537, 538,   6,   7, 539, 540]]) tensor([37])
tensor([[ 75,  29,  30, 702]]) tensor([37])
tensor([[ 75,  71, 656,  91,   6, 657, 658]]) tensor([ 54,  90,  71, 656,  91,   6, 657, 658])
tensor([[ 75, 316, 317,  12, 318, 128, 319]]) tensor([37])
tensor([[ 65, 649, 619, 482,   6]]) tensor([ 54, 619, 205,   6, 409, 650,   6, 122, 523, 640])
tensor([[ 20, 458,   7, 556,  42, 726,  66, 727, 728]]) tensor([37])
tensor([[  5,  38,  66, 179, 180,  26, 181, 182, 183]]) tensor([37])
tensor([[  5,   7, 223, 224, 225,  42,   7, 217, 224]]) tensor([37])
tensor([[  1, 420, 229,  19,  66, 421, 422,  12, 423, 424, 211, 425,  97, 426]]) tensor([  7, 263, 427, 428, 429, 430, 431, 432,  42, 433, 229,  66, 245,  97,
        434, 435, 436, 437,  12,   7, 438, 439])
tensor([[ 1, 40,  7, 41, 42, 43, 44, 45, 46]]) tensor([ 7, 47, 12, 48, 18])
tensor([[226,  20, 348, 659, 660]]) tensor([492,  20, 348, 659, 660])
tensor([[  5, 265,   7, 352,   2]]) tensor([37])
tensor([[ 49, 333, 282, 334,  42, 335, 336]]) tensor([37])
tensor([[184,  66, 199, 200, 201, 202, 203, 204, 205]]) tensor([  6,   7, 206,  66, 199, 207, 208, 200, 201, 202, 203, 204, 205])
tensor([[  5, 786,  66, 787,   2]]) tensor([37])
tensor([[ 55,  75, 158, 159, 160,  56, 161]]) tensor([162, 163,  26, 164, 165, 166, 167])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 2, 9]]) tensor([10])
tensor([[ 75, 734, 735,  42,   7, 736, 737]]) tensor([37])
tensor([[ 97,  24, 443,   5, 488, 489]]) tensor([488,   5, 489,  97, 392, 488, 490, 488,  26, 366, 488])
tensor([[117,  49,  85, 521, 522]]) tensor([523, 524])
tensor([[  1,  49, 366, 224, 187, 338,  12]]) tensor([367, 368, 369, 208, 370, 371, 372])
tensor([[  1,   5,   7, 583, 584, 585,   6, 586]]) tensor([587, 588, 589, 590, 591, 592, 593])
tensor([[ 75, 696, 697, 698, 699]]) tensor([700, 701])
tensor([[  1,   5, 135,  57, 654,  12]]) tensor([655])
tensor([[651, 209, 652, 577, 653]]) tensor([37])
tensor([[ 55,  86, 641,  49, 642, 643]]) tensor([])
tensor([[  5,  57, 352,   2,  12,  38, 627]]) tensor([54, 19,  5, 90])
tensor([[ 55,  86, 126,  75, 127, 128]]) tensor([])
tensor([[  1,  75, 511,  29,  30]]) tensor([511,  29,  30,  66, 747,  12, 702,  26,  31, 211, 748, 211, 749, 524,
        750,  26, 751])
tensor([[ 55,  86, 628, 629,  65, 630, 631, 632, 633, 634, 630, 635, 301, 636,
         533, 637, 211,  66, 556, 208, 638,   2]]) tensor([628, 629])
tensor([[  1, 504,  12,   7, 549,   5,   7, 550]]) tensor([  7, 551,  12,  66, 549])
tensor([[ 64,  65,  87, 189, 190,  97, 191,  26, 192]]) tensor([])
tensor([[  5,  57, 158, 565, 566]]) tensor([37])
tensor([[75, 76, 77, 78, 79, 80]]) tensor([37])
tensor([[  5,   7,  41, 646, 435,   7, 647, 509, 648]]) tensor([37])
tensor([[ 5, 81, 66, 82, 42, 83,  7, 84, 12, 66, 85]]) tensor([37])
tensor([[  1, 703,   6]]) tensor([704, 704, 704])
tensor([[ 24, 340,  45,  65, 341, 342, 343, 344,   6,   7, 345]]) tensor([346,  45])
tensor([[  1,  20, 710, 711, 712]]) tensor([713, 714])
tensor([[  5,  66, 567,  66, 568]]) tensor([37])
tensor([[ 20, 409, 410, 411,  12,   7, 412, 413]]) tensor([37])
tensor([[  1,   5,   7, 738, 454, 162, 453, 739,  42, 740]]) tensor([  7, 556, 741])
tensor([[184,   7, 661, 662,   7, 617, 663, 664, 211,   7, 665,  12, 401, 336]]) tensor([  7, 661, 666,   7, 617, 663, 664, 211,   7, 665,  12, 401, 336])
tensor([[ 1,  5,  7, 16, 12, 17, 18]]) tensor([19, 20,  7, 21, 22, 23, 24, 25, 26, 27,  7, 18,  6, 26])
tensor([[ 55,  49, 541, 542, 543]]) tensor([162,  66, 544, 545, 546,  26, 547, 548])
tensor([[ 55,  56,   5,  66, 280, 281]]) tensor([42, 62])
tensor([[  1,   5,   7, 497, 498,  12, 499]]) tensor([500, 501])
tensor([[  5, 196, 173, 197,  42, 198, 173]]) tensor([196, 173,   5, 197,  42, 198, 173])
tensor([[ 65, 690, 691, 692,   7, 366, 185]]) tensor([37])
tensor([[ 55, 392,  20, 680,  64, 209, 205]]) tensor([])
tensor([[ 49, 106, 133,   6, 677, 678]]) tensor([37])
tensor([[ 49, 109, 110, 111, 112]]) tensor([37])
tensor([[ 65, 129, 114,   7, 130,  12, 131, 132]]) tensor([37])
tensor([[  5, 168, 169,  42, 170, 171, 172]]) tensor([37])
tensor([[  1,   5,   7, 267, 268, 269, 270]]) tensor([ 81,  49, 271,  24, 272, 123, 267,   6, 273, 268, 269, 270,  26, 274,
        275])
tensor([[  5,   7, 770,  57, 392, 444, 771]]) tensor([37])
tensor([[ 64,  65, 492, 556, 302, 211, 639]]) tensor([640])
tensor([[226,   5,   7, 232,  12, 233]]) tensor([234, 235])
tensor([[ 49, 512, 513, 514, 515, 513]]) tensor([37])
tensor([[  1, 389, 390,   7, 391,  12,   7, 392, 393, 394]]) tensor([  7, 391,  12,   7, 392, 393, 394,  20, 390, 162,   7, 395,  12,   7,
        396, 397, 162, 398, 399, 400])
tensor([[ 20, 715, 716, 518, 717,  12, 718, 491, 141, 142]]) tensor([37])
tensor([[  1,   5, 133,  42, 134,  66, 135]]) tensor([  7, 136])
tensor([[ 5, 38, 39]]) tensor([37])
tensor([[117,  20, 137, 138,  97]]) tensor([141, 142,  41])
tensor([[  5, 780,   7, 481, 781,  12,   7, 780, 631]]) tensor([37])
tensor([[226,  20, 468, 268, 469,   6, 470, 471,  12, 162, 472, 473]]) tensor([457, 458])
tensor([[  5,   7, 681, 682,   7, 683, 682]]) tensor([54])
tensor([[20, 34, 35, 36]]) tensor([37])
tensor([[  5, 414, 415,   7, 416, 417,  12, 323]]) tensor([37])
tensor([[ 20, 209, 210, 211,  66, 212, 213, 214]]) tensor([ 37, 209,  20, 210, 211,  66, 212, 213, 214])
tensor([[117,  20, 137, 138,  97]]) tensor([139, 140,  12, 141, 142,  41])

In [34]:
import torch.nn as nn

In [35]:
# X = nn.Embedding(544,embedding_dim=50)
# Y = nn.RNN(50,64,batch_first = True)
# Z = nn.Linear(64,544)

# # step 1 data

# a = dataset[0][0].reshape(1,3)
# print(f"Shape of a: {a.shape}")
# b = X(a) # 50 dim
# print(f"Shape of b: {b.shape}")
# c , d = Y(b) # RNN
# print(f"Shape of c :{c.shape} \nShape of d : {d.shape}")

# e = Z(d.squeeze(0))
# print(f"Shape of e: {e.shape}")

In [36]:
# Model Building 
# Simple RNN

class SimpleRNN(nn.Module):

    def __init__(self,vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,embedding_dim=50)
        self.rnn = nn.RNN(50,64,batch_first=True)
        self.fc = nn.Linear(64,vocab_size)

    def forward(self,question):
        embedded_question = self.embedding(question)
        hidden , final = self.rnn(embedded_question)
        output = self.fc(final.squeeze(0))

        return output

In [37]:
learning_rate = 0.001
epochs = 100

In [38]:
model = SimpleRNN(len(vocab))

In [39]:
# loss , optimizer 

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [41]:
# for q,a in dataloader:
#     print(a)
#     print("1d :-",a.flatten())
#     print("scaler vaule :-",a.flatten()[0])
#     print("unsqueeze(0)  :-",a.flatten()[0].unsqueeze(0) )
#     break

In [42]:
for epoch in range(epochs):
    total_loss = 0
    for question, answer in dataloader:

        if answer.numel() == 0:
            continue

        optimizer.zero_grad()

        output = model(question)                    # [1, vocab_size]
        target = answer.flatten()[0].unsqueeze(0)   # [1]  ← fixed

        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch: {epoch+1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 868.3240
Epoch: 2, Loss: 465.6113
Epoch: 3, Loss: 396.8719
Epoch: 4, Loss: 350.0307
Epoch: 5, Loss: 302.0195
Epoch: 6, Loss: 250.2417
Epoch: 7, Loss: 198.7329
Epoch: 8, Loss: 153.2116
Epoch: 9, Loss: 114.9199
Epoch: 10, Loss: 84.9141
Epoch: 11, Loss: 62.6070
Epoch: 12, Loss: 46.2117
Epoch: 13, Loss: 35.2285
Epoch: 14, Loss: 27.6426
Epoch: 15, Loss: 22.0569
Epoch: 16, Loss: 18.2186
Epoch: 17, Loss: 14.9094
Epoch: 18, Loss: 13.7570
Epoch: 19, Loss: 14.5334
Epoch: 20, Loss: 10.6004
Epoch: 21, Loss: 8.5726
Epoch: 22, Loss: 7.5448
Epoch: 23, Loss: 6.7718
Epoch: 24, Loss: 6.1429
Epoch: 25, Loss: 5.8813
Epoch: 26, Loss: 5.1502
Epoch: 27, Loss: 4.6561
Epoch: 28, Loss: 4.7439
Epoch: 29, Loss: 4.4728
Epoch: 30, Loss: 4.1863
Epoch: 31, Loss: 3.8673
Epoch: 32, Loss: 3.8118
Epoch: 33, Loss: 3.5999
Epoch: 34, Loss: 3.4684
Epoch: 35, Loss: 3.3060
Epoch: 36, Loss: 3.2018
Epoch: 37, Loss: 3.0979
Epoch: 38, Loss: 3.0012
Epoch: 39, Loss: 2.8537
Epoch: 40, Loss: 2.8186
Epoch: 41, Loss: 2.7509
Epoch: 42, Loss: 2.5959
Epoch: 43, Loss: 2.6069
Epoch: 44, Loss: 2.1725
Epoch: 45, Loss: 2.5364
Epoch: 46, Loss: 2.4813
Epoch: 47, Loss: 2.2471
Epoch: 48, Loss: 2.4109
Epoch: 49, Loss: 2.3527
Epoch: 50, Loss: 2.3493
Epoch: 51, Loss: 2.3545
Epoch: 52, Loss: 2.2151
Epoch: 53, Loss: 2.2484
Epoch: 54, Loss: 2.2521
Epoch: 55, Loss: 2.0752
Epoch: 56, Loss: 2.1474
Epoch: 57, Loss: 2.1020
Epoch: 58, Loss: 2.1556
Epoch: 59, Loss: 2.1581
Epoch: 60, Loss: 2.1811
Epoch: 61, Loss: 2.0940
Epoch: 62, Loss: 2.0492
Epoch: 63, Loss: 2.0337
Epoch: 64, Loss: 2.0150
Epoch: 65, Loss: 2.0117
Epoch: 66, Loss: 2.0384
Epoch: 67, Loss: 2.0758
Epoch: 68, Loss: 2.0754
Epoch: 69, Loss: 2.0102
Epoch: 70, Loss: 1.9501
Epoch: 71, Loss: 1.9227
Epoch: 72, Loss: 1.7077
Epoch: 73, Loss: 1.9428
Epoch: 74, Loss: 1.9663
Epoch: 75, Loss: 2.0293
Epoch: 76, Loss: 2.0280
Epoch: 77, Loss: 1.9702
Epoch: 78, Loss: 1.9729
Epoch: 79, Loss: 1.4949
Epoch: 80, Loss: 1.9659
Epoch: 81, Loss: 1.9581
Epoch: 82, Loss: 1.9753
Epoch: 83, Loss: 1.8738
Epoch: 84, Loss: 1.9175
Epoch: 85, Loss: 1.9293
Epoch: 86, Loss: 1.9063
Epoch: 87, Loss: 1.9315
Epoch: 88, Loss: 1.9501
Epoch: 89, Loss: 1.9558
Epoch: 90, Loss: 1.8222
Epoch: 91, Loss: 1.9304
Epoch: 92, Loss: 1.8393
Epoch: 93, Loss: 1.6276
Epoch: 94, Loss: 1.8781
Epoch: 95, Loss: 1.9034
Epoch: 96, Loss: 1.9010
Epoch: 97, Loss: 1.6217
Epoch: 98, Loss: 1.8327
Epoch: 99, Loss: 1.8718
Epoch: 100, Loss: 1.7396

In [46]:
Q_1 = model(torch.tensor(text_to_indices(df['Question'][0],vocab)).unsqueeze(0))
prob = torch.nn.functional.softmax(Q_1,dim=1)
torch.max(prob,dim=1)

torch.return_types.max(
values=tensor([0.9999], grad_fn=<MaxBackward0>),
indices=tensor([10]))

In [47]:
list(vocab)[5]

'is'

In [48]:
def predict(model,question,vocab,threshold=0.5):
    model.eval()

    with torch.no_grad():
        numberical_question = text_to_indices(question,vocab)

        # shape [1,seq_len]
        question_tensor = torch.tensor(numberical_question).unsqueeze(0)

        output = model(question_tensor)

        # probabilities
        probs = torch.nn.functional.softmax(output,dim=1)

        # Get top probabilitie
        value , index = torch.max(probs,dim=1)
        print(f"Value :- {value},Index :- {index}")

        confidence = value.item()
        pred_idx = index.item()

        if confidence < threshold:
            print("I don't Know")
            return None
        # Answer 
        predicted_word = list(vocab.keys())[pred_idx]
        print(f'Predicted : {predicted_word} (confidence : {confidence:.2f})')
        return predicted_word

In [49]:
df

,Question,Answer
0,What language besides Malay is in the Austrone...,Malagasy
1,What percentage of Liechtenstein's population ...,67%
2,What is the cause of local earthquakes?,It was the San Andreas Fault which slipped and...
3,Sea otters eat what?,Shellfish and other invertebrates
4,Was Calvin Coolidge Republican?,Yes
...,...,...
145,Has Urbanization eliminated many areas of form...,Yes
146,Is Vietnamese the mother tongue of the Vietnam...,Yes
147,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...
148,Is Swahili a Bantu language?,yes
149,Are there many Roma in Romania?,No.

In [53]:
text = df['Question'][0] 

df['Question'][0] ," ",df['Answer'][0]

('What language besides Malay is in the Austronesia language family?',
 ' ',
 'Malagasy')

In [54]:
predict(model,text,vocab,threshold=0.5)

Value :- tensor([0.9999]),Index :- tensor([10])
Predicted : malagasy (confidence : 1.00)

'malagasy'