https://www.kaggle.com/datasets/rtatman/questionanswer-dataset/data?select=S08_question_answer_pairs.txt

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('data/text-data/S08_question_answer_pairs.txt',sep='\t')
df1

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,yes,easy,easy,S08_set3_a4
1,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,Yes.,easy,easy,S08_set3_a4
2,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,yes,easy,medium,S08_set3_a4
3,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,Yes.,easy,easy,S08_set3_a4
4,Abraham_Lincoln,Did his mother die of pneumonia?,no,easy,medium,S08_set3_a4
...,...,...,...,...,...,...
1710,Woodrow_Wilson,Was Wilson president of the American Political...,Yes,NaN,easy,S08_set3_a8
1711,Woodrow_Wilson,Did he not cast his ballot for John M. Palmer ...,Yes,NaN,easy,S08_set3_a8
1712,Woodrow_Wilson,Did Wilson not spend 1914 through the beginnin...,Yes,NaN,easy,S08_set3_a8
1713,Woodrow_Wilson,"Was Wilson , a staunch opponent of antisemitis...",Yes,NaN,easy,S08_set3_a8
1714,Woodrow_Wilson,What happened in 1917?,"raised billions through Liberty loans, imposed...",NaN,medium,S08_set3_a8

In [3]:
df2 = pd.read_csv('data/text-data/S09_question_answer_pairs.txt',sep='\t')
df2

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
1,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
2,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
3,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
4,Alessandro_Volta,Did Volta have a passion for the study of elec...,yes,easy,medium,S09_set4_a10
...,...,...,...,...,...,...
820,Xylophone,What is the earliest historical reference in E...,Arnold Schlick's Spiegel der Orgelmacher und O...,medium,medium,S09_set2_a8
821,Xylophone,How are western-style xylophones characterised?,"by a bright, sharp tone and high register",medium,medium,S09_set2_a8
822,Xylophone,Can a xylophone be 3 octaves?,yes,hard,hard,S09_set2_a8
823,Xylophone,Can a short bar follow a long bar?,no,hard,hard,S09_set2_a8
824,Xylophone,Did vibraphones exist in 1930?,yes,hard,hard,S09_set2_a8

In [4]:
df3 = pd.read_csv('data/text-data/S10_question_answer_pairs.txt',sep='\t',encoding='latin-1')
df3

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,Alessandro Volta was not a professor of chemis...,easy,easy,S10_set4_a10
1,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,No,easy,hard,S10_set4_a10
2,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...,easy,easy,S10_set4_a10
3,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Yes,easy,easy,S10_set4_a10
4,Alessandro_Volta,Was Alessandro Volta taught in public schools?,Volta was taught in public schools.,easy,easy,S10_set4_a10
...,...,...,...,...,...,...
1453,Zebra,What areas do the Grevy's Zebras inhabit?,NaN,hard,NaN,S10_set1_a9
1454,Zebra,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur...",hard,medium,S10_set1_a9
1455,Zebra,Which species of zebra is known as the common ...,Plains Zebra,hard,medium,S10_set1_a9
1456,Zebra,At what age can a zebra breed?,five or six,hard,medium,S10_set1_a9
1457,Zebra,At what age can a zebra breed?,5 or 6,hard,hard,S10_set1_a9

In [5]:
df1.shape,df2.shape,df3.shape

((1715, 6), (825, 6), (1458, 6))

In [6]:
1715 + 825 + 1458

3998

In [7]:
df = pd.concat(
    [df1,df2,df3],
)[['Question','Answer']]

In [8]:
df.isnull().sum()

Question     37
Answer      578
dtype: int64

In [9]:
df = df.dropna(axis=0)

In [10]:
df = df.sample(150).reset_index(drop=True)

In [11]:
df

,Question,Answer
0,"Who was the first gymnast to score a perfect ""...",Nadia Comăneci
1,Is it true that he published his invention of ...,Yes
2,What happened in the early 20th century?,The koalas of South Australia were largely ext...
3,Who did James Monroe marry?,Elizabeth Kortright
4,How many regions is Ghana divided into?,10
...,...,...
145,Is the Polar Bear the mascot of Bowdoin college ?,yes
146,Did Volta have a passion for the study of elec...,yes
147,Is Ghana's head of state John Agyekum Kufuor?,yes
148,Did Coolidge get in Amherst College?,Yes
149,Was Tesla regarded as a mad scientist?,yes

In [12]:
import re

In [13]:
def tokenize(text):
    if isinstance(text, str): 
        text = text.lower()
        
        # We added \d to the brackets to catch all numbers
        # Alternatively, you could write 0-9 inside the brackets
        text = re.sub(r'[!-@#$%^&*()_+><:;?\'\d]', '', text)
        
        return text.split()
    return text

In [14]:
tokenize(df['Question'][4])

['how', 'many', 'regions', 'is', 'ghana', 'divided', 'into']

In [15]:
# Vocab (for unknow words)

vocab = {'<UNK>':0}

In [30]:
def build_vocab(row):
    # if pd.isna(row['Question']) or pd.isna(row['Answer']):
    #     return

    tokenized_question = tokenize(row['Question'])
    tokenized_answer = tokenize(row['Answer'])

    for token in tokenized_question + tokenized_answer:
        if token not in vocab:
            vocab[token] = len(vocab)

In [31]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
145    None
146    None
147    None
148    None
149    None
Length: 150, dtype: object

In [32]:
len(vocab)

798

In [33]:
vocab

{'<UNK>': 0,
 'who': 1,
 'was': 2,
 'the': 3,
 'first': 4,
 'gymnast': 5,
 'to': 6,
 'score': 7,
 'a': 8,
 'perfect': 9,
 'ten': 10,
 'nadia': 11,
 'comăneci': 12,
 'is': 13,
 'it': 14,
 'true': 15,
 'that': 16,
 'he': 17,
 'published': 18,
 'his': 19,
 'invention': 20,
 'of': 21,
 'voltaic': 22,
 'pile': 23,
 'battery': 24,
 'yes': 25,
 'what': 26,
 'happened': 27,
 'in': 28,
 'early': 29,
 'th': 30,
 'century': 31,
 'koalas': 32,
 'south': 33,
 'australia': 34,
 'were': 35,
 'largely': 36,
 'exterminated': 37,
 'did': 38,
 'james': 39,
 'monroe': 40,
 'marry': 41,
 'elizabeth': 42,
 'kortright': 43,
 'how': 44,
 'many': 45,
 'regions': 46,
 'ghana': 47,
 'divided': 48,
 'into': 49,
 'victor': 50,
 'war': 51,
 'currents': 52,
 'nikola': 53,
 'tesla': 54,
 'when': 55,
 'monroes': 56,
 'presidency': 57,
 'expired': 58,
 'march': 59,
 'indonesia': 60,
 'has': 61,
 'vast': 62,
 'areas': 63,
 'wilderness': 64,
 'dismantled': 65,
 'partisan': 66,
 'and': 67,
 'sectional': 68,
 'coalitions': 69,
 'congressmen': 70,
 'international': 71,
 'airports': 72,
 'does': 73,
 'montreal': 74,
 'have': 75,
 'two': 76,
 'kangaroo': 77,
 'marsupial': 78,
 'from': 79,
 'family': 80,
 'macropodidae': 81,
 'lrb': 82,
 'macropods': 83,
 'meaning': 84,
 '``': 85,
 '`': 86,
 'large': 87,
 'foot': 88,
 'rrb': 89,
 'strings': 90,
 'classical': 91,
 'lyre': 92,
 'made': 93,
 'gut': 94,
 'john': 95,
 'adams': 96,
 'go': 97,
 'harvard': 98,
 'do': 99,
 'trumpets': 100,
 'compensate': 101,
 'for': 102,
 'wolf': 103,
 'tones': 104,
 'somce': 105,
 'trumpetes': 106,
 'slide': 107,
 'mechanism': 108,
 'built': 109,
 'are': 110,
 'young': 111,
 'swans': 112,
 'known': 113,
 'as': 114,
 'cygnets': 115,
 'there': 116,
 'more': 117,
 'industrialized': 118,
 'region': 119,
 'malaysia': 120,
 'no': 121,
 'vespoid': 122,
 'wasps': 123,
 'evolve': 124,
 'predatory': 125,
 'ancestors': 126,
 'long': 127,
 'classification': 128,
 'dialects': 129,
 'spoken': 130,
 'outside': 131,
 'finland': 132,
 'been': 133,
 'controversial': 134,
 'issue': 135,
 'since': 136,
 'finlands': 137,
 'independence': 138,
 'team': 139,
 'sedating': 140,
 'cleveland': 141,
 'with': 142,
 'nitrous': 143,
 'oxide': 144,
 'laughing': 145,
 'gas': 146,
 'not': 147,
 'remove': 148,
 'upper': 149,
 'left': 150,
 'jaw': 151,
 'portions': 152,
 'hard': 153,
 'palate': 154,
 'elephants': 155,
 'largest': 156,
 'land': 157,
 'animals': 158,
 'alive': 159,
 'today': 160,
 'bees': 161,
 'related': 162,
 'ants': 163,
 'butterflies': 164,
 'carry': 165,
 'pollen': 166,
 'than': 167,
 'hymenoptera': 168,
 'less': 169,
 'penguins': 170,
 'birds': 171,
 'watt': 172,
 'french': 173,
 'scottish': 174,
 'calvin': 175,
 'coolidge': 176,
 'republican': 177,
 'linguists': 178,
 'consider': 179,
 'malay': 180,
 'be': 181,
 'single': 182,
 'language': 183,
 'san': 184,
 'lorenzo': 185,
 'megaport': 186,
 'project': 187,
 'completed': 188,
 'charlesaugustin': 189,
 'de': 190,
 'coulomb': 191,
 'live': 192,
 'years': 193,
 'old': 194,
 'polar': 195,
 'bears': 196,
 'guard': 197,
 'hair': 198,
 'cm': 199,
 'good': 200,
 'swimmers': 201,
 'swedish': 202,
 'counterbalance': 203,
 'absence': 204,
 'cases': 205,
 'lack': 206,
 'compensated': 207,
 'by': 208,
 'wide': 209,
 'variety': 210,
 'prepositions': 211,
 'otters': 212,
 'water': 213,
 'romania': 214,
 'declare': 215,
 'neutrality': 216,
 'during': 217,
 'world': 218,
 'i': 219,
 'die': 220,
 'july': 221,
 'gellu': 222,
 'naum': 223,
 'leader': 224,
 'surrealist': 225,
 'movement': 226,
 'whats': 227,
 'timber': 228,
 'ancient': 229,
 'cimbals': 230,
 'like': 231,
 'disfluent': 232,
 'small': 233,
 'handbells': 234,
 'or': 235,
 'notes': 236,
 'keyed': 237,
 'harmonica': 238,
 'difference': 239,
 'between': 240,
 'leopards': 241,
 'cheetahs': 242,
 'leopard': 243,
 'rossettes': 244,
 'rather': 245,
 'simple': 246,
 'spots': 247,
 'but': 248,
 'they': 249,
 'internal': 250,
 'unlike': 251,
 'jaguar': 252,
 'larger': 253,
 'lanky': 254,
 'cheetah': 255,
 'smaller': 256,
 'ride': 257,
 'cymbals': 258,
 'very': 259,
 'common': 260,
 'giant': 261,
 'pandas': 262,
 'genome': 263,
 'sequenced': 264,
 'wisma': 265,
 'building': 266,
 'tallest': 267,
 'kangaroos': 268,
 'powerful': 269,
 'hind': 270,
 'legs': 271,
 'feet': 272,
 'adapted': 273,
 'leaping': 274,
 'muscular': 275,
 'tail': 276,
 'balance': 277,
 'head': 278,
 'eucalypt': 279,
 'forests': 280,
 'grow': 281,
 'place': 282,
 'rainforests': 283,
 'koala': 284,
 'specialise': 285,
 'diet': 286,
 'eucalyptus': 287,
 'until': 288,
 'climate': 289,
 'cooled': 290,
 'grew': 291,
 'state': 292,
 'agyekum': 293,
 'kufuor': 294,
 'official': 295,
 'iraq': 296,
 'capital': 297,
 'city': 298,
 'oslo': 299,
 'before': 300,
 'being': 301,
 'elected': 302,
 'governor': 303,
 'practiced': 304,
 'law': 305,
 'virginia': 306,
 'all': 307,
 'turtles': 308,
 'tortoises': 309,
 'breathe': 310,
 'air': 311,
 'ford': 312,
 'need': 313,
 'extra': 314,
 'work': 315,
 'pay': 316,
 'college': 317,
 'drives': 318,
 'sea': 319,
 'otter': 320,
 'almost': 321,
 'extinction': 322,
 'humans': 323,
 'hunted': 324,
 'them': 325,
 'drum': 326,
 'member': 327,
 'percussion': 328,
 'group': 329,
 'violin': 330,
 'usually': 331,
 'four': 332,
 'similarities': 333,
 'beetles': 334,
 'grasshoppers': 335,
 'mouthparts': 336,
 'swahili': 337,
 'bantu': 338,
 'may': 339,
 'happen': 340,
 'red': 341,
 'fire': 342,
 'if': 343,
 'we': 344,
 'use': 345,
 'boiling': 346,
 'on': 347,
 'queen': 348,
 'most': 349,
 'popular': 350,
 'sport': 351,
 'ice': 352,
 'hockey': 353,
 'thermometer': 354,
 'had': 355,
 'freezing': 356,
 'point': 357,
 'finding': 358,
 'another': 359,
 'lover': 360,
 'jacqueline': 361,
 'roque': 362,
 'picasso': 363,
 'species': 364,
 'commonly': 365,
 'referred': 366,
 'eastern': 367,
 'grey': 368,
 'western': 369,
 'antilopine': 370,
 'charles': 371,
 'augustin': 372,
 'born': 373,
 'june': 374,
 'angoulême': 375,
 'france': 376,
 'died': 377,
 'august': 378,
 'paris': 379,
 'physicist': 380,
 'millard': 381,
 'fillmore': 382,
 'thirteenth': 383,
 'president': 384,
 'united': 385,
 'states': 386,
 'along': 387,
 'citys': 388,
 'border': 389,
 'taipei': 390,
 'danshui': 391,
 'river': 392,
 'its': 393,
 'testudines': 394,
 'crown': 395,
 'superorder': 396,
 'chelonia': 397,
 'travel': 398,
 'walking': 399,
 'eat': 400,
 'fish': 401,
 'shellfish': 402,
 'well': 403,
 'mammals': 404,
 'tz': 405,
 'indicate': 406,
 'preceding': 407,
 'vowel': 408,
 'short': 409,
 'which': 410,
 'sports': 411,
 'events': 412,
 'olympiastadion': 413,
 'host': 414,
 'summer': 415,
 'olympics': 416,
 'fifa': 417,
 'cup': 418,
 'final': 419,
 'constellation': 420,
 'said': 421,
 'resemble': 422,
 'shape': 423,
 'lyra': 424,
 'farmer': 425,
 'later': 426,
 'surveyor': 427,
 'government': 428,
 'leroy': 429,
 'pollock': 430,
 'volta': 431,
 'an': 432,
 'italian': 433,
 'ago': 434,
 'luther': 435,
 'bible': 436,
 'martin': 437,
 'printed': 438,
 'santiago': 439,
 'spanish': 440,
 'st': 441,
 'santo': 442,
 'saint': 443,
 'iago': 444,
 'native': 445,
 'pronunciation': 446,
 'qatar': 447,
 'sound': 448,
 'cutter': 449,
 'jakarta': 450,
 'examined': 451,
 'longevity': 452,
 'genes': 453,
 'main': 454,
 'varieties': 455,
 'indian': 456,
 'flutes': 457,
 'currently': 458,
 'used': 459,
 'matti': 460,
 'vanhanen': 461,
 'prime': 462,
 'minister': 463,
 'came': 464,
 'xylophone': 465,
 'vibraphone': 466,
 'word': 467,
 'mean': 468,
 'warrior': 469,
 'king': 470,
 'why': 471,
 'wasnt': 472,
 'neutral': 473,
 'ii': 474,
 'received': 475,
 'soviet': 476,
 'ultimatum': 477,
 'produce': 478,
 'produces': 479,
 'textiles': 480,
 'apparel': 481,
 'electronics': 482,
 'machinery': 483,
 'materials': 484,
 'precision': 485,
 'equipment': 486,
 'food': 487,
 'beverages': 488,
 'eagle': 489,
 'scout': 490,
 'introduce': 491,
 'doctrine': 492,
 'december': 493,
 'give': 494,
 'example': 495,
 'origins': 496,
 'term': 497,
 'action': 498,
 'painting': 499,
 'pollocks': 500,
 'technique': 501,
 'pouring': 502,
 'dripping': 503,
 'paint': 504,
 'thought': 505,
 'one': 506,
 'definition': 507,
 'electrostatic': 508,
 'force': 509,
 'attraction': 510,
 'repulsion': 511,
 'coulombs': 512,
 'second': 513,
 'biggest': 514,
 'factor': 515,
 'affecting': 516,
 'produced': 517,
 'tension': 518,
 'lobsters': 519,
 'blue': 520,
 'blood': 521,
 'become': 522,
 'chief': 523,
 'engineer': 524,
 'department': 525,
 'bridges': 526,
 'highways': 527,
 'grover': 528,
 'twentyseventh': 529,
 'whose': 530,
 'continual': 531,
 'poor': 532,
 'health': 533,
 'cause': 534,
 'never': 535,
 'precisely': 536,
 'determined': 537,
 'blaise': 538,
 'pascal': 539,
 'population': 540,
 'copenhagen': 541,
 'henri': 542,
 'becquerel': 543,
 'where': 544,
 'francisco': 545,
 'california': 546,
 'municipalities': 547,
 'within': 548,
 'oberland': 549,
 'cartier': 550,
 'canada': 551,
 'refer': 552,
 'only': 553,
 'village': 554,
 'entire': 555,
 'area': 556,
 'subject': 557,
 'donnacona': 558,
 'at': 559,
 'stadacona': 560,
 'lincolns': 561,
 'wifes': 562,
 'support': 563,
 'slavery': 564,
 'based': 565,
 'moden': 566,
 'orchestras': 567,
 'ottawas': 568,
 'junior': 569,
 'ottawa': 570,
 's': 571,
 'country': 572,
 'portuguese': 573,
 'coofficial': 574,
 'cantonese': 575,
 'chinese': 576,
 'macau': 577,
 'aside': 578,
 'provincial': 579,
 'letters': 580,
 'religious': 581,
 'influence': 582,
 'literary': 583,
 'national': 584,
 'winter': 585,
 'lacrosse': 586,
 'number': 587,
 'page': 588,
 'extensively': 589,
 'celebrated': 590,
 'holiday': 591,
 'christmas': 592,
 'denmark': 593,
 'celsius': 594,
 'crater': 595,
 'moon': 596,
 'named': 597,
 'after': 598,
 'him': 599,
 'amedeo': 600,
 'avogadro`s': 601,
 'birthplace': 602,
 'turin': 603,
 'name': 604,
 'watts': 605,
 'mother': 606,
 'agnes': 607,
 'muirhead': 608,
 'si': 609,
 'unit': 610,
 'charge': 611,
 'current': 612,
 'estimated': 613,
 'nairobi': 614,
 'about': 615,
 'million': 616,
 'beneficial': 617,
 'alpha': 618,
 'males': 619,
 'females': 620,
 'forcefully': 621,
 'prevent': 622,
 'other': 623,
 'wolves': 624,
 'mating': 625,
 'pack': 626,
 'rises': 627,
 'each': 628,
 'mature': 629,
 'feels': 630,
 'urged': 631,
 'mate': 632,
 'completely': 633,
 'surrounded': 634,
 'isaac': 635,
 'newton': 636,
 'clear': 637,
 'german': 638,
 'written': 639,
 'using': 640,
 'latin': 641,
 'alphabet': 642,
 'ideas': 643,
 'enlightenment': 644,
 'shaped': 645,
 'development': 646,
 'uruguay': 647,
 'located': 648,
 'america': 649,
 'southeastern': 650,
 'part': 651,
 'founded': 652,
 'montevideo': 653,
 'military': 654,
 'stronghold': 655,
 'semipresidential': 656,
 'democratic': 657,
 'republic': 658,
 'executive': 659,
 'functions': 660,
 'shared': 661,
 'trumpet': 662,
 'constructed': 663,
 'brass': 664,
 'tubing': 665,
 'can': 666,
 'guitars': 667,
 'broad': 668,
 'categories': 669,
 'much': 670,
 'weigh': 671,
 'considerably': 672,
 'kg': 673,
 'compared': 674,
 'faraday': 675,
 'wrote': 676,
 'letter': 677,
 'times': 678,
 'foul': 679,
 'condition': 680,
 'thames': 681,
 'resulted': 682,
 'oftreprinted': 683,
 'cartoon': 684,
 'punch': 685,
 'leonardo': 686,
 'da': 687,
 'vinci': 688,
 'april': 689,
 'hihats': 690,
 'crash': 691,
 'splash': 692,
 'china': 693,
 'electric': 694,
 'guitar': 695,
 'bodies': 696,
 'wood': 697,
 'jeanbaptiste': 698,
 'arban': 699,
 'complete': 700,
 'conservatory': 701,
 'method': 702,
 'male': 703,
 'giraffes': 704,
 'female': 705,
 'highest': 706,
 'growth': 707,
 'rates': 708,
 'any': 709,
 'africa': 710,
 'rate': 711,
 'cello': 712,
 '�basso': 713,
 'viola': 714,
 'braccio': 715,
 'monteverdi': 716,
 'economy': 717,
 'sure': 718,
 'answer': 719,
 'this': 720,
 'standard': 721,
 'living': 722,
 'franciscio': 723,
 'high': 724,
 'wedding': 725,
 'trinity': 726,
 'church': 727,
 'new': 728,
 'york': 729,
 'delta': 730,
 'traditionally': 731,
 'nghe': 732,
 'ha': 733,
 'tinh': 734,
 'quang': 735,
 'binh': 736,
 'panda': 737,
 'terrestrial': 738,
 'animal': 739,
 'protect': 740,
 'vehicale': 741,
 'roo': 742,
 'bars': 743,
 'helped': 744,
 'un': 745,
 'peacekeeping': 746,
 'efforts': 747,
 'played': 748,
 'leading': 749,
 'role': 750,
 'suez': 751,
 'crisis': 752,
 'lester': 753,
 'b': 754,
 'pearson': 755,
 'eased': 756,
 'tensions': 757,
 'proposing': 758,
 'inception': 759,
 'nations': 760,
 'served': 761,
 'missions': 762,
 'including': 763,
 'every': 764,
 'effort': 765,
 'trains': 766,
 'stop': 767,
 'daily': 768,
 'beijing': 769,
 'railway': 770,
 'station': 771,
 'west': 772,
 'order': 773,
 'include': 774,
 'both': 775,
 'extant': 776,
 'extinct': 777,
 'earliest': 778,
 'around': 779,
 'guiana': 780,
 'year': 781,
 'east': 782,
 'timor': 783,
 'secede': 784,
 'beside': 785,
 'bear': 786,
 'mascot': 787,
 'bowdoin': 788,
 'passion': 789,
 'study': 790,
 'electricity': 791,
 'ghanas': 792,
 'get': 793,
 'amherst': 794,
 'regarded': 795,
 'mad': 796,
 'scientist': 797}

In [34]:
def text_to_indices(text, vocab):

    return [
        vocab.get(token, vocab['<UNK>'])
        for token in tokenize(text)
    ]

In [35]:
df['Question'][0]

'Who was the first gymnast to score a perfect "ten"?'

In [36]:
text_to_indices(df['Question'][0],vocab)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
df

,Question,Answer
0,"Who was the first gymnast to score a perfect ""...",Nadia Comăneci
1,Is it true that he published his invention of ...,Yes
2,What happened in the early 20th century?,The koalas of South Australia were largely ext...
3,Who did James Monroe marry?,Elizabeth Kortright
4,How many regions is Ghana divided into?,10
...,...,...
145,Is the Polar Bear the mascot of Bowdoin college ?,yes
146,Did Volta have a passion for the study of elec...,yes
147,Is Ghana's head of state John Agyekum Kufuor?,yes
148,Did Coolidge get in Amherst College?,Yes
149,Was Tesla regarded as a mad scientist?,yes

In [38]:
df.iloc[0]['Question']

'Who was the first gymnast to score a perfect "ten"?'

In [39]:
import torch
from torch.utils.data import DataLoader , Dataset

In [40]:
class QADataset(Dataset):

    def __init__(self,df,vocab):
        self.df = df
        self.vocab = vocab

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self,index):

        numerical_question = text_to_indices(self.df.iloc[index]['Question'],self.vocab)
        numerical_answer = text_to_indices(self.df.iloc[index]['Answer'],self.vocab)

        return torch.tensor(numerical_question) , torch.tensor(numerical_answer)

In [41]:
dataset = QADataset(df,vocab)

In [42]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [43]:
for question , answer in dataloader:
    print(question,answer[0])

tensor([[26, 35,  3, 90, 21,  8, 91, 92, 93, 21]]) tensor([94])
tensor([[ 13,  60,   8, 658]]) tensor([25])
tensor([[ 44,  99, 349, 163, 398]]) tensor([349, 163, 398, 208, 399])
tensor([[44, 45, 46, 13, 47, 48, 49]]) tensor([])
tensor([[ 21, 530, 531, 532, 533,   2,   3, 534, 535, 536, 537]]) tensor([538, 539])
tensor([[ 38, 176, 793,  28, 794, 317]]) tensor([25])
tensor([[ 99, 212, 192,  28, 213]]) tensor([25])
tensor([[ 26,  13,   3, 297,  21,  60]]) tensor([450])
tensor([[ 13,   3, 326,   8, 327,  21,   3, 328, 329]]) tensor([25])
tensor([[ 1,  2,  3, 50, 21,  3, 51, 21, 52]]) tensor([53, 54])
tensor([[110, 308, 301, 451, 102, 452, 453]]) tensor([25])
tensor([[ 73,   3, 773, 394, 147, 774, 775, 776,  82, 722,  89,  67, 777, 364,
           3, 778, 113, 308, 301,  79, 779, 616, 193, 434]]) tensor([25])
tensor([[13, 14, 15, 16, 60, 61, 62, 63, 21, 64]]) tensor([25])
tensor([[  1,  13,   3, 278,  21, 292,  21,  47]]) tensor([ 95, 293, 294])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) tensor([11, 12])
tensor([[ 44, 127,  13, 195, 196, 197, 198]]) tensor([199])
tensor([[  2, 431, 432, 433, 380]]) tensor([25])
tensor([[ 26,  38,  39,  40,  99, 300, 301, 302, 303]]) tensor([ 17, 304, 305,  28, 306])
tensor([[  2,  54, 795, 114,   8, 796, 797]]) tensor([25])
tensor([[ 13, 638, 639, 640,   3, 641, 642]]) tensor([25])
tensor([[ 13, 439, 440, 102, 441,  39,  79, 442, 443, 444,  39]]) tensor([25])
tensor([[110, 258, 459,  28, 566, 567]]) tensor([25])
tensor([[ 26, 318, 319, 320, 321,   6, 322]]) tensor([323, 324, 325, 321,   6, 322])
tensor([[38, 95, 96, 97,  6, 98]]) tensor([25])
tensor([[  2, 371, 372, 190, 191, 373, 374, 375, 376, 377, 378, 379, 376,   8,
         173, 380]]) tensor([25])
tensor([[666, 667, 181,  48,  49,  76, 668, 669]]) tensor([25])
tensor([[  2, 312, 432, 489, 490]]) tensor([25])
tensor([[ 13,   3, 341, 392, 730, 731, 532]]) tensor([147, 674,   6, 732, 432, 733, 734, 235, 735, 736])
tensor([[  2, 528, 141,   3, 529, 384,  21,   3, 385, 386]]) tensor([121])
tensor([[544,  99, 319, 212, 192]]) tensor([785, 213])
tensor([[ 44,  45, 454, 455,  21, 456, 457, 110, 458, 459]]) tensor([76])
tensor([[ 26, 110,   3, 349, 260, 258]]) tensor([  3, 349, 260, 258, 110,   3, 690, 691, 692, 257,  67, 693])
tensor([[  1, 652, 653]]) tensor([653,   2, 652, 208,   3, 440,  28,   3,  29,  30,  31, 114,   8, 654,
        655])
tensor([[ 28,  26, 781,  38, 782, 783, 784,  79,  60]]) tensor([])
tensor([[ 26,  13,   3, 513, 514, 515, 516,   3, 448, 517, 208,   8, 326]]) tensor([518])
tensor([[ 26,  73,   3, 467,  47, 468]]) tensor([469, 470])
tensor([[ 26,  13,   3, 540,  21, 541]]) tensor([])
tensor([[ 44,  38, 122, 123, 124]]) tensor([ 79, 125, 126])
tensor([[541,  13,   3, 297,  21,  26, 572]]) tensor([593])
tensor([[ 38, 550, 147, 345,   3, 467,  86, 551,   6, 552,   6, 147, 553,  16,
         554, 248,   3, 555, 556, 557,   6, 558, 523, 559, 560]]) tensor([25])
tensor([[ 26,  13,   3, 239, 240, 241,  67, 242]]) tensor([  3, 243,  61, 244, 245, 167, 242, 246, 247, 248, 249, 206, 250, 247,
        251,   3, 252,   3, 243,  13, 253,  67, 169, 254, 167,   3, 255, 248,
        256, 167,   3, 252])
tensor([[ 99, 519,  75, 520, 521]]) tensor([25])
tensor([[ 26,  13, 512, 305]]) tensor([  3, 507,  21,   3, 508, 509,  21, 510,  67, 511])
tensor([[227,   3, 228,  21, 229, 230, 231, 232]]) tensor([231,  16,  21, 233, 234, 235,  21,   3, 236,  21,   3, 237, 238])
tensor([[ 38, 561, 562,  80, 563, 564]]) tensor([25])
tensor([[ 13,   3, 721,  21, 722,  28, 184, 723, 724]]) tensor([25])
tensor([[ 13, 337,   8, 338, 183]]) tensor([ 25, 337,  13,   8, 338, 183])
tensor([[ 1, 38, 39, 40, 41]]) tensor([42, 43])
tensor([[ 26,  99, 307, 308,  67, 309, 310]]) tensor([311])
tensor([[ 26,  13,   3, 507,  21,   3, 508, 509,  21, 510,  67, 511]]) tensor([512, 305,  13,   3, 507,  21,   3, 508, 509,  21, 510,  67, 511])
tensor([[ 28, 410, 572,  13, 573,   3, 574, 183, 142, 575, 576]]) tensor([573,  13,   3, 574, 183, 142, 575, 576,  28, 577])
tensor([[110, 155, 200, 201]]) tensor([25])
tensor([[ 13, 792, 278,  21, 292,  95, 293, 294]]) tensor([25])
tensor([[ 38,  40, 725, 340, 559,   3, 726, 727,  28, 728, 729]]) tensor([25])
tensor([[ 26,  13, 568, 569, 352, 353, 139]]) tensor([  3, 570, 571])
tensor([[ 26,  13,   3, 349, 589, 590, 591]]) tensor([592,  13,   3, 349, 589, 590, 591])
tensor([[ 13,   3, 594, 595, 347,   3, 596, 597, 598, 599]]) tensor([25])
tensor([[ 55,  38,  39,  40, 491,   3,  40, 492]]) tensor([493])
tensor([[ 26, 110,   3, 333, 240, 334,  67, 335]]) tensor([336])
tensor([[ 44,  73, 202, 183, 203,   3, 204,  21, 205]]) tensor([  3, 206,  21, 205,  28, 202,  13, 207, 208,   8, 209, 210,  21, 211])
tensor([[110, 551, 571, 295, 584, 411, 352, 353, 585,  67, 586, 415]]) tensor([25])
tensor([[ 13,   3, 297, 298, 299]]) tensor([121])
tensor([[ 73,   8, 405, 406,  16,   3, 407, 408,  13, 409]]) tensor([121])
tensor([[ 26,  13, 459,   6, 740,   8, 741,  79,   8,  77]]) tensor([742, 743])
tensor([[ 13,   3, 349, 350, 351,  28,  74, 352, 353]]) tensor([ 25,   3, 349, 350, 351,  28,  74,  13, 352, 353])
tensor([[ 38,  17, 522, 523, 524,  28,   3, 525,  21, 526,  67, 527,  28]]) tensor([121])
tensor([[ 1, 65, 66, 67, 68, 69]]) tensor([45, 70])
tensor([[ 26, 110, 349, 694, 695, 696,  93,  21]]) tensor([697])
tensor([[ 38, 279, 280, 281,  28,   3, 282,  21, 283]]) tensor([ 25,   3, 284,  38, 147, 285,  28,   8, 286,  21, 287, 288,   3, 289,
        290,  67, 279, 280, 291,  28,   3, 282,  21, 283])
tensor([[110, 161, 162,   6, 163]]) tensor([25])
tensor([[494, 432, 495,  21,   3, 706, 707, 708,  21, 709, 298,  28, 710]]) tensor([  3, 707, 711,  21, 614,  13, 458, 432, 495,  21,   3, 706, 707, 708,
         21, 709, 298,  28, 710])
tensor([[110, 155,   3, 156, 157, 158, 159, 160]]) tensor([25])
tensor([[ 13,   3, 195, 786,   3, 787,  21, 788, 317]]) tensor([25])
tensor([[ 26, 110, 111, 112, 113, 114]]) tensor([115])
tensor([[ 44,  45, 193, 434,   2,  14,  55, 675, 676,   8, 677,   6,   3, 678,
         347,   3, 557,  21,   3, 679, 680,  21,   3, 392, 681, 410, 682,  28,
         432, 683, 684,  28, 685]]) tensor([])
tensor([[114,  21, 378, 441,  44,  45, 766, 767, 768, 559,   3, 769, 770, 771,
         235,   3, 769, 772, 770, 771]]) tensor([])
tensor([[ 13,   3, 261, 737,   8, 738, 739]]) tensor([25])
tensor([[410, 464,   4,   3, 465, 235,   3, 466]]) tensor([465])
tensor([[ 13,  14,  15,  16, 354, 355, 102,   3, 356, 357]]) tensor([25])
tensor([[110, 257, 258, 259, 260]]) tensor([25])
tensor([[ 38, 214, 215, 216, 217, 218,  51, 219]]) tensor([25])
tensor([[13,  8, 77,  8, 78, 79,  3, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]]) tensor([25])
tensor([[110, 170, 171]]) tensor([25])
tensor([[ 26,  13,   3, 612, 613, 540,  21, 614]]) tensor([615, 616])
tensor([[ 38, 431,  75,   8, 789, 102,   3, 790,  21, 791]]) tensor([25])
tensor([[ 44,  45, 547, 110, 548, 549]]) tensor([])
tensor([[  2, 175, 176, 177]]) tensor([25])
tensor([[ 26,  13,   3,   4, 587, 347,   3, 588]]) tensor([])
tensor([[  2,   3, 609, 610,  21, 611,   3, 191, 597, 598, 599]]) tensor([25])
tensor([[ 26,  99, 717,  67, 305,  75,  28, 260]]) tensor([147, 718,  44,   6, 719, 720])
tensor([[ 38,   3, 139, 140, 141, 142, 143, 144,  82, 145, 146,  89, 147, 148,
          19, 149, 150, 151,  67, 152,  21,  19, 153, 154]]) tensor([25])
tensor([[ 13,  14,  15,  16,   3, 643,  21,   3, 644, 645,   3, 646,  21,   3,
         298]]) tensor([25])
tensor([[471, 472, 214, 473, 217, 218,  51, 474]]) tensor([ 14, 475,   8, 476, 477])
tensor([[26, 27, 28]]) tensor([698, 699,  18, 700, 701, 702, 102, 662])
tensor([[ 99, 703, 704, 671, 117, 167, 705, 704]]) tensor([25])
tensor([[ 26,   2,   3, 604,  21,  39, 605, 606]]) tensor([607, 608])
tensor([[410, 420,  13, 421,   6, 422,   8,  92, 423]]) tensor([424])
tensor([[ 38, 189, 190, 191, 192,   6, 181, 193, 194]]) tensor([121])
tensor([[ 99, 178, 179, 180,   6, 181,   8, 182, 183]]) tensor([121])
tensor([[410,  76, 411, 412,  38,   3, 413, 414]]) tensor([  3, 415, 416,  67,   3, 417, 218, 418, 419])
tensor([[102,  44, 127,  61,   3, 128,  21, 129, 130, 131,  21, 132, 133,   8,
         134, 135]]) tensor([  3, 128,  21, 129, 130, 131,  21, 132,  61, 133,   8, 134, 135, 136,
        137, 138,  28])
tensor([[55, 38, 56, 57, 58]]) tensor([59])
tensor([[  2, 222, 223,   3, 224,  21,   3, 225, 226,  28, 214]]) tensor([25])
tensor([[  2, 635, 636, 581]]) tensor([ 14,  13, 147, 637])
tensor([[ 13,  39, 172, 173]]) tensor([121,  17,   2, 174])
tensor([[ 26,  13,   8, 662, 663,  21]]) tensor([664, 665])
tensor([[ 26,   2, 600, 601, 602]]) tensor([603])
tensor([[494, 432, 495,  21,   3, 496,  21,   3, 497, 498, 499]]) tensor([500, 501,  21, 502,  67, 503, 504,  13, 505,   6, 181, 506,  21,   3,
        496,  21,   3, 497, 498, 499])
tensor([[  2, 542, 543,   8, 173, 380]]) tensor([25])
tensor([[ 44,  61, 551, 744, 745, 746, 747]]) tensor([551,  61, 748,   8, 749, 750,  28, 745, 746, 747, 217,   3, 751, 752,
         21, 753, 754, 755, 756, 757, 208, 758,   3, 759,  21,   3, 385, 760,
        746, 509, 551,  61, 136, 761,  28, 746, 762, 763, 764, 745, 746, 765,
        288])
tensor([[44, 45, 71, 72, 73, 74, 75]]) tensor([74, 61, 76, 71, 72])
tensor([[ 13, 647, 648,  28,  33, 649]]) tensor([ 25, 393, 648,  28,   3, 650, 651])
tensor([[ 26, 339, 340,   6, 341, 342, 163, 343, 344, 345, 346, 213, 347,   3,
         348]]) tensor([220])
tensor([[ 26, 110, 332, 364,  16, 110, 365, 366,   6, 114, 268]]) tensor([  3, 341,  77,   3, 367, 368,  77,   3, 369, 368,  77,  67,   3, 370,
         77])
tensor([[26, 27, 28,  3, 29, 30, 31]]) tensor([ 3, 32, 21, 33, 34, 35, 36, 37])
tensor([[ 44,  99, 100, 101, 102, 103, 104]]) tensor([105, 106,  75,   8, 107, 108, 109,  28,   6, 101])
tensor([[ 44,  99, 349, 163, 398]]) tensor([208, 399])
tensor([[ 38, 312, 313,   6,  99, 314, 315,   6, 316, 102, 317]]) tensor([25])
tensor([[ 13, 460, 461,   3, 462, 463,  21, 132]]) tensor([25])
tensor([[ 44, 194,   2, 542, 543,  55,  17, 377]]) tensor([])
tensor([[ 75, 268,  87, 269, 270, 271,  87, 272, 273, 102, 274,   8, 127, 275,
         276, 102, 277,  67,   8, 233, 278]]) tensor([25])
tensor([[ 13, 116,   8, 117, 118, 119,  28, 120]]) tensor([121])
tensor([[ 61,   3, 184, 185, 186, 187, 133, 188]]) tensor([121])
tensor([[  1, 366,   6,   3, 712, 114, 713, 190, 714, 687, 715]]) tensor([716])
tensor([[110, 394,   3, 395, 329,  21,   3, 396, 397]]) tensor([25])
tensor([[ 73,   3, 445, 446,  21, 447, 448, 231, 449]]) tensor([121])
tensor([[ 55,   2,   3, 261, 262, 263, 264]]) tensor([])
tensor([[ 26,  73, 390, 478]]) tensor([390, 479, 480, 481, 482, 483, 438, 484, 485, 486, 487,  67, 488])
tensor([[ 13, 180,   3, 295, 183,  21, 296]]) tensor([121])
tensor([[ 13,   3, 265, 266,   3, 267, 266,  28,  60]]) tensor([25])
tensor([[472, 686, 687, 688, 373, 347, 689]]) tensor([ 25, 686, 687, 688,   2, 373, 347, 689])
tensor([[471,  13,  14, 617, 102, 618, 619,  67, 620,   6, 621, 622, 623, 624,
          79, 625]]) tensor([  3, 626, 518, 627, 114, 628, 629, 103, 630, 631,   6, 632])
tensor([[ 13, 214,   8, 656, 657, 658, 544, 659, 660, 110, 661, 240,   3, 384,
          67,   3, 462, 463]]) tensor([25])
tensor([[  1,   2,   8, 425,  67, 426,   8, 157, 427, 102,   3, 428]]) tensor([429, 430,   2,   8, 425,  67, 426,   8, 157, 427, 102,   3, 428])
tensor([[ 44,  45,  90,  73,   8, 330, 331,  75]]) tensor([332])
tensor([[ 73, 647, 389, 173, 780]]) tensor([121])
tensor([[578,  79,   3, 579, 580, 581, 582,  35, 249, 350, 114,   8, 583, 315]]) tensor([25])
tensor([[ 44, 670,  73,   8, 243, 671]]) tensor([619, 110, 672, 253, 167, 620,  67, 671,   6, 673, 674,   6,   6, 673,
        102, 620])
tensor([[ 55,  38,  39,  40, 220]]) tensor([221])
tensor([[13, 14, 15, 16, 17, 18, 19, 20, 21,  3, 22, 23, 24]]) tensor([25])
tensor([[  1,   2, 147, 127,  28, 358, 359, 360, 361, 362]]) tensor([363])
tensor([[ 44,  45, 193, 434,   2,   3, 435, 436, 208, 437, 435, 438]]) tensor([])
tensor([[110, 309, 157, 565]]) tensor([25])
tensor([[  2, 381, 382,   3, 383, 384,  21,   3, 385, 386]]) tensor([25])
tensor([[ 99, 164, 165, 117, 166, 167, 168]]) tensor([121, 164, 165, 169, 166, 167, 168])
tensor([[ 26,  99, 392, 212, 400]]) tensor([  8, 210,  21, 401,  67, 402, 114, 403, 114, 233, 157, 404,  67, 171])
tensor([[ 26,  13, 387,   3, 388, 369, 389]]) tensor([390,  61,   3, 391, 392, 387, 393, 369, 389])
tensor([[110, 258, 459,  28, 566, 567]]) tensor([25])
tensor([[544,  13, 184, 545]]) tensor([184, 545,  13,  28, 546])
tensor([[ 13, 541, 633, 634, 142, 213]]) tensor([121])