https://www.kaggle.com/datasets/rtatman/questionanswer-dataset/data?select=S08_question_answer_pairs.txt

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('data/text-data/S08_question_answer_pairs.txt',sep='\t')
df1

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,yes,easy,easy,S08_set3_a4
1,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,Yes.,easy,easy,S08_set3_a4
2,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,yes,easy,medium,S08_set3_a4
3,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,Yes.,easy,easy,S08_set3_a4
4,Abraham_Lincoln,Did his mother die of pneumonia?,no,easy,medium,S08_set3_a4
...,...,...,...,...,...,...
1710,Woodrow_Wilson,Was Wilson president of the American Political...,Yes,NaN,easy,S08_set3_a8
1711,Woodrow_Wilson,Did he not cast his ballot for John M. Palmer ...,Yes,NaN,easy,S08_set3_a8
1712,Woodrow_Wilson,Did Wilson not spend 1914 through the beginnin...,Yes,NaN,easy,S08_set3_a8
1713,Woodrow_Wilson,"Was Wilson , a staunch opponent of antisemitis...",Yes,NaN,easy,S08_set3_a8
1714,Woodrow_Wilson,What happened in 1917?,"raised billions through Liberty loans, imposed...",NaN,medium,S08_set3_a8

In [3]:
df2 = pd.read_csv('data/text-data/S09_question_answer_pairs.txt',sep='\t')
df2

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
1,Alessandro_Volta,Was Volta an Italian physicist?,yes,easy,easy,S09_set4_a10
2,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
3,Alessandro_Volta,Is Volta buried in the city of Pittsburgh?,no,easy,easy,S09_set4_a10
4,Alessandro_Volta,Did Volta have a passion for the study of elec...,yes,easy,medium,S09_set4_a10
...,...,...,...,...,...,...
820,Xylophone,What is the earliest historical reference in E...,Arnold Schlick's Spiegel der Orgelmacher und O...,medium,medium,S09_set2_a8
821,Xylophone,How are western-style xylophones characterised?,"by a bright, sharp tone and high register",medium,medium,S09_set2_a8
822,Xylophone,Can a xylophone be 3 octaves?,yes,hard,hard,S09_set2_a8
823,Xylophone,Can a short bar follow a long bar?,no,hard,hard,S09_set2_a8
824,Xylophone,Did vibraphones exist in 1930?,yes,hard,hard,S09_set2_a8

In [4]:
df3 = pd.read_csv('data/text-data/S10_question_answer_pairs.txt',sep='\t',encoding='latin-1')
df3

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,Alessandro Volta was not a professor of chemis...,easy,easy,S10_set4_a10
1,Alessandro_Volta,Was Alessandro Volta a professor of chemistry?,No,easy,hard,S10_set4_a10
2,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Alessandro Volta did invent the remotely opera...,easy,easy,S10_set4_a10
3,Alessandro_Volta,Did Alessandro Volta invent the remotely opera...,Yes,easy,easy,S10_set4_a10
4,Alessandro_Volta,Was Alessandro Volta taught in public schools?,Volta was taught in public schools.,easy,easy,S10_set4_a10
...,...,...,...,...,...,...
1453,Zebra,What areas do the Grevy's Zebras inhabit?,NaN,hard,NaN,S10_set1_a9
1454,Zebra,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur...",hard,medium,S10_set1_a9
1455,Zebra,Which species of zebra is known as the common ...,Plains Zebra,hard,medium,S10_set1_a9
1456,Zebra,At what age can a zebra breed?,five or six,hard,medium,S10_set1_a9
1457,Zebra,At what age can a zebra breed?,5 or 6,hard,hard,S10_set1_a9

In [5]:
df1.shape,df2.shape,df3.shape

((1715, 6), (825, 6), (1458, 6))

In [6]:
1715 + 825 + 1458

3998

In [7]:
df = pd.concat(
    [df1,df2,df3],axis=0
)[['Question','Answer']]

In [8]:
df

,Question,Answer
0,Was Abraham Lincoln the sixteenth President of...,yes
1,Was Abraham Lincoln the sixteenth President of...,Yes.
2,Did Lincoln sign the National Banking Act of 1...,yes
3,Did Lincoln sign the National Banking Act of 1...,Yes.
4,Did his mother die of pneumonia?,no
...,...,...
1453,What areas do the Grevy's Zebras inhabit?,NaN
1454,Which species of zebra is known as the common ...,"Plains Zebra (Equus quagga, formerly Equus bur..."
1455,Which species of zebra is known as the common ...,Plains Zebra
1456,At what age can a zebra breed?,five or six
1457,At what age can a zebra breed?,5 or 6

In [9]:
sum(df['Answer'].value_counts().head(6).values)

np.int64(1367)

In [10]:
df.isnull().sum()

Question     37
Answer      578
dtype: int64

In [11]:
df = df.dropna(axis=0)

In [12]:
df.shape

(3420, 2)

In [13]:
df = df.sample(200).reset_index(drop=True)

In [14]:
df

,Question,Answer
0,Is it true that he sent in federal troops to c...,yes
1,Was Amedeo Avogadro was born in Turin?,yes
2,What happened in the early 20th century?,The koalas of South Australia were largely ext...
3,What are the reasons for hunting wild ducks?,"Meat, eggs, and feathers"
4,Has tusklessness become a rare abnormality?,"No, tusklessness has become a widespread hered..."
...,...,...
195,Did James Monroe attend the College of William...,Yes
196,What did Cleveland die from?,A heart attack
197,Is it true that he became a professor in 1820?,yes
198,When did Watt retire?,In 1800.
199,Has tusklessness become a rare abnormality?,No

In [18]:
import re

In [19]:
def tokenize(text):
    if isinstance(text, str): 
        text = text.lower()
        
        # We added \d to the brackets to catch all numbers
        # Alternatively, you could write 0-9 inside the brackets
        text = re.sub(r'[!-@#$%^&*()_+><:;?\'\d]', '', text)
        
        return text.split()
    return text

In [20]:
tokenize(df['Question'][0])

['is',
 'it',
 'true',
 'that',
 'he',
 'sent',
 'in',
 'federal',
 'troops',
 'to',
 'chicago']

In [21]:
# Vocab

vocab = {'<PAD>':0,'SOS':1,'EOS':2,'<UNK>':3}

In [22]:
def build_vocab(row):

    tokenized_question = tokenize(row['Question'])
    tokenized_answer = tokenize(row['Answer'])

    for token in tokenized_question + tokenized_answer:
        if token not in vocab:
            vocab[token] = len(vocab)

In [23]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
195    None
196    None
197    None
198    None
199    None
Length: 200, dtype: object

In [24]:
len(vocab)

1057

In [27]:
vocab

{'<PAD>': 0,
 'SOS': 1,
 'EOS': 2,
 '<UNK>': 3,
 'is': 4,
 'it': 5,
 'true': 6,
 'that': 7,
 'he': 8,
 'sent': 9,
 'in': 10,
 'federal': 11,
 'troops': 12,
 'to': 13,
 'chicago': 14,
 'yes': 15,
 'was': 16,
 'amedeo': 17,
 'avogadro': 18,
 'born': 19,
 'turin': 20,
 'what': 21,
 'happened': 22,
 'the': 23,
 'early': 24,
 'th': 25,
 'century': 26,
 'koalas': 27,
 'of': 28,
 'south': 29,
 'australia': 30,
 'were': 31,
 'largely': 32,
 'exterminated': 33,
 'are': 34,
 'reasons': 35,
 'for': 36,
 'hunting': 37,
 'wild': 38,
 'ducks': 39,
 'meat': 40,
 'eggs': 41,
 'and': 42,
 'feathers': 43,
 'has': 44,
 'tusklessness': 45,
 'become': 46,
 'a': 47,
 'rare': 48,
 'abnormality': 49,
 'no': 50,
 'widespread': 51,
 'hereditary': 52,
 'trait': 53,
 'does': 54,
 'each': 55,
 'type': 56,
 'drum': 57,
 'head': 58,
 'serve': 59,
 'its': 60,
 'own': 61,
 'musical': 62,
 'purpose': 63,
 'nineteen': 64,
 'fifty': 65,
 'seven': 66,
 'maynard': 67,
 'ferguson': 68,
 'formed': 69,
 'his': 70,
 'band': 71,
 'president': 72,
 'elected': 73,
 'by': 74,
 'popular': 75,
 'vote': 76,
 'how': 77,
 'long': 78,
 'classification': 79,
 'dialects': 80,
 'spoken': 81,
 'outside': 82,
 'finland': 83,
 'been': 84,
 'controversial': 85,
 'issue': 86,
 'since': 87,
 'finlands': 88,
 'independence': 89,
 'hutongs': 90,
 'disappearing': 91,
 'do': 92,
 'octopuses': 93,
 'less': 94,
 'familiar': 95,
 'cirrina': 96,
 'suborder': 97,
 'have': 98,
 'two': 99,
 'fins': 100,
 'an': 101,
 'internal': 102,
 'shell': 103,
 'uruguays': 104,
 'capital': 105,
 'montevideo': 106,
 'life': 107,
 'expectancy': 108,
 'men': 109,
 'years': 110,
 'beetles': 111,
 'endopterygotes': 112,
 'giant': 113,
 'pandas': 114,
 'attack': 115,
 'humans': 116,
 'which': 117,
 'ballet': 118,
 'pyotr': 119,
 'tchaikovsky': 120,
 'partially': 121,
 'based': 122,
 'on': 123,
 'ancient': 124,
 'german': 125,
 'legend': 126,
 'about': 127,
 'princess': 128,
 'who': 129,
 'turned': 130,
 'into': 131,
 'swan': 132,
 'lake': 133,
 'happens': 134,
 'if': 135,
 'wing': 136,
 'removed': 137,
 'ring': 138,
 'other': 139,
 'three': 140,
 'will': 141,
 'grow': 142,
 'larger': 143,
 'size': 144,
 'nassau': 145,
 'coliseum': 146,
 'arena': 147,
 'uniondale': 148,
 'new': 149,
 'york': 150,
 'usa': 151,
 'when': 152,
 'did': 153,
 'beijing': 154,
 'host': 155,
 'olympic': 156,
 'games': 157,
 'all': 158,
 'quack': 159,
 'newspapers': 160,
 'respond': 161,
 'roosevelt': 162,
 'inviting': 163,
 'brooker': 164,
 't': 165,
 'washington': 166,
 'dinner': 167,
 'at': 168,
 'white': 169,
 'house': 170,
 'they': 171,
 'outraged': 172,
 'dialect': 173,
 'jeju': 174,
 'located': 175,
 'fact': 176,
 'classified': 177,
 'as': 178,
 'different': 179,
 'language': 180,
 'korean': 181,
 'linguists': 182,
 'some': 183,
 'where': 184,
 'deepest': 185,
 'note': 186,
 'classical': 187,
 'lyre': 188,
 'relation': 189,
 'players': 190,
 'body': 191,
 'farthest': 192,
 'from': 193,
 'arabic': 194,
 'major': 195,
 'vehicle': 196,
 'culture': 197,
 'europe': 198,
 'largest': 199,
 'religious': 200,
 'group': 201,
 'canada': 202,
 'christian': 203,
 'helped': 204,
 'un': 205,
 'peacekeeping': 206,
 'efforts': 207,
 'during': 208,
 'suez': 209,
 'crisis': 210,
 'lester': 211,
 'b': 212,
 'pearson': 213,
 'eased': 214,
 'tensions': 215,
 'proposing': 216,
 'inception': 217,
 'united': 218,
 'nations': 219,
 'force': 220,
 'served': 221,
 'missions': 222,
 'including': 223,
 'every': 224,
 'effort': 225,
 'until': 226,
 'semiaquatic': 227,
 'marine': 228,
 'mammal': 229,
 'polar': 230,
 'bear': 231,
 'adapted': 232,
 'combination': 233,
 'land': 234,
 'sea': 235,
 'ice': 236,
 'battery': 237,
 'made': 238,
 'alessandro': 239,
 'volta': 240,
 'credited': 241,
 'first': 242,
 'electrochemical': 243,
 'cell': 244,
 'oil': 245,
 'gas': 246,
 'probably': 247,
 'remain': 248,
 'backbone': 249,
 'qatar': 250,
 's': 251,
 'economy': 252,
 'time': 253,
 'come': 254,
 'many': 255,
 'siblings': 256,
 'nikola': 257,
 'tesla': 258,
 'had': 259,
 'four': 260,
 'otters': 261,
 'herbivores': 262,
 'romania': 263,
 'declare': 264,
 'neutrality': 265,
 'world': 266,
 'war': 267,
 'i': 268,
 'dutch': 269,
 'build': 270,
 'elmina': 271,
 'castle': 272,
 'movie': 273,
 'surviving': 274,
 'picasso': 275,
 'played': 276,
 'actor': 277,
 'anthony': 278,
 'hopkins': 279,
 'isaac': 280,
 'newton': 281,
 'british': 282,
 'english': 283,
 'professor': 284,
 'university': 285,
 'pavia': 286,
 'almost': 287,
 'jakarta': 288,
 'indonesias': 289,
 'special': 290,
 'region': 291,
 'node': 292,
 'integer': 293,
 'division': 294,
 'string': 295,
 'octopus': 296,
 'eyes': 297,
 'si': 298,
 'unit': 299,
 'measuring': 300,
 'magnetic': 301,
 'flux': 302,
 'density': 303,
 'or': 304,
 'induction': 305,
 'faraday': 306,
 'also': 307,
 'discover': 308,
 'laws': 309,
 'electrolysis': 310,
 'discovered': 311,
 'why': 312,
 'occupy': 313,
 'copenhagen': 314,
 'because': 315,
 'ww': 316,
 'airports': 317,
 'kuala': 318,
 'lumpur': 319,
 'international': 320,
 'airport': 321,
 'subang': 322,
 'populations': 323,
 'extend': 324,
 'considerable': 325,
 'distances': 326,
 'inland': 327,
 'regions': 328,
 'with': 329,
 'enough': 330,
 'moisture': 331,
 'support': 332,
 'suitable': 333,
 'woodlands': 334,
 'crissy': 335,
 'field': 336,
 'airfield': 337,
 'standard': 338,
 'piano': 339,
 'fewer': 340,
 'strings': 341,
 'than': 342,
 'harp': 343,
 'adams': 344,
 'opponent': 345,
 'stamp': 346,
 'act': 347,
 'trumpet': 348,
 'constructed': 349,
 'brass': 350,
 'tubing': 351,
 'middle': 352,
 'chinese': 353,
 'used': 354,
 'through': 355,
 'centuries': 356,
 'ce': 357,
 'works': 358,
 'enjoy': 359,
 'broad': 360,
 'appeal': 361,
 'states': 362,
 'rockwell': 363,
 'most': 364,
 'famous': 365,
 'cover': 366,
 'illustrations': 367,
 'everyday': 368,
 'scenarios': 369,
 'created': 370,
 'saturday': 371,
 'evening': 372,
 'post': 373,
 'magazine': 374,
 'over': 375,
 'more': 376,
 'decades': 377,
 'only': 378,
 'tortoises': 379,
 'seychelles': 380,
 'gal�pagos': 381,
 'islands': 382,
 'arrived': 383,
 'britain': 384,
 'canadian': 385,
 'army': 386,
 'units': 387,
 'ii': 388,
 'published': 389,
 'collection': 390,
 'observations': 391,
 'heavily': 392,
 'influenced': 393,
 'architecture': 394,
 'european': 395,
 'immigrants': 396,
 'taught': 397,
 'public': 398,
 'schools': 399,
 'considered': 400,
 'gentleman': 401,
 'ago': 402,
 'lima': 403,
 'stock': 404,
 'exchange': 405,
 'profitable': 406,
 'swans': 407,
 'feature': 408,
 'strongly': 409,
 'mythology': 410,
 'recognizable': 411,
 'company': 412,
 'employer': 413,
 'common': 414,
 'hilti': 415,
 'ref': 416,
 'swahili': 417,
 'unusual': 418,
 'among': 419,
 'subsaharan': 420,
 'languages': 421,
 'portuguese': 422,
 'roots': 423,
 'latin': 424,
 'derived': 425,
 'population': 426,
 'city': 427,
 'antwerp': 428,
 'antwerps': 429,
 'monroe': 430,
 'wedding': 431,
 'happen': 432,
 'trinity': 433,
 'church': 434,
 'widely': 435,
 'lebanese': 436,
 'especially': 437,
 'administrative': 438,
 'purposes': 439,
 'french': 440,
 'henri': 441,
 'becquerel': 442,
 'one': 443,
 'discoverers': 444,
 'radioactivity': 445,
 'information': 446,
 'record': 447,
 'diary': 448,
 'descriptions': 449,
 'events': 450,
 'ompressions': 451,
 'colonial': 452,
 'buildings': 453,
 'toward': 454,
 'end': 455,
 'related': 456,
 'islam': 457,
 'liturgical': 458,
 'turtles': 459,
 'lay': 460,
 'their': 461,
 'holes': 462,
 'dug': 463,
 'mud': 464,
 'sand': 465,
 'national': 466,
 'palace': 467,
 'museum': 468,
 'taipei': 469,
 'became': 470,
 'third': 471,
 'family': 472,
 'physics': 473,
 'chair': 474,
 'musum': 475,
 'd`histoire': 476,
 'naturelle': 477,
 'bust': 478,
 'queen': 479,
 'nefertiti': 480,
 'altes': 481,
 'can': 482,
 'flutes': 483,
 'volume': 484,
 'be': 485,
 'increased': 486,
 'making': 487,
 'resonator': 488,
 'tone': 489,
 'ottawa': 490,
 'colder': 491,
 'moscow': 492,
 'january': 493,
 'possible': 494,
 'alter': 495,
 'word': 496,
 'order': 497,
 'stress': 498,
 'importance': 499,
 'certain': 500,
 'phrase': 501,
 'alive': 502,
 'today': 503,
 'old': 504,
 'would': 505,
 'share': 506,
 'border': 507,
 'ukraine': 508,
 'before': 509,
 'lombardy': 510,
 'ruled': 511,
 'austria': 512,
 'basic': 513,
 'malay': 514,
 'subject': 515,
 'verb': 516,
 'object': 517,
 'naturalists': 518,
 'distinguish': 519,
 'between': 520,
 'leopards': 521,
 'panthers': 522,
 'length': 523,
 'tail': 524,
 'having': 525,
 'longer': 526,
 'tails': 527,
 'abraham': 528,
 'lincoln': 529,
 'sixteenth': 530,
 'asian': 531,
 'elephants': 532,
 'pacific': 533,
 'typhoon': 534,
 'season': 535,
 'june': 536,
 'october': 537,
 'dominant': 538,
 'religion': 539,
 'ghana': 540,
 'books': 541,
 'maps': 542,
 'began': 543,
 'referring': 544,
 'this': 545,
 'year': 546,
 'die': 547,
 'kangaroos': 548,
 'wide': 549,
 'bite': 550,
 'sides': 551,
 'lower': 552,
 'jaw': 553,
 'not': 554,
 'joined': 555,
 'together': 556,
 'incisors': 557,
 'farther': 558,
 'apart': 559,
 'count': 560,
 'breathe': 561,
 'air': 562,
 'characterized': 563,
 'large': 564,
 'multifaceted': 565,
 'pairs': 566,
 'strong': 567,
 'transparent': 568,
 'wings': 569,
 'elongated': 570,
 'bequerel': 571,
 'win': 572,
 'nobel': 573,
 'prize': 574,
 'discoverer': 575,
 'center': 576,
 'cymbal': 577,
 'hit': 578,
 'causes': 579,
 'sound': 580,
 'higher': 581,
 'register': 582,
 'rest': 583,
 'flute': 584,
 'player': 585,
 'change': 586,
 'pitch': 587,
 'opening': 588,
 'closing': 589,
 'instrument': 590,
 'thedore': 591,
 'member': 592,
 'republican': 593,
 'party': 594,
 'resembles': 595,
 'similarlysized': 596,
 'cougar': 597,
 'americas': 598,
 'ecological': 599,
 'role': 600,
 'now': 601,
 'part': 602,
 'historical': 603,
 'park': 604,
 'john': 605,
 'birthplace': 606,
 'belgium': 607,
 'however': 608,
 'quatrevingts': 609,
 'universally': 610,
 'diving': 611,
 'heavier': 612,
 'tha': 613,
 'dabbling': 614,
 'caunte': 615,
 'take': 616,
 'control': 617,
 'throne': 618,
 'aside': 619,
 'provincial': 620,
 'letters': 621,
 'influence': 622,
 'literary': 623,
 'work': 624,
 'whats': 625,
 'million': 626,
 'boiling': 627,
 'point': 628,
 'water': 629,
 'dependent': 630,
 'atmospheric': 631,
 'pressure': 632,
 'guitars': 633,
 'divided': 634,
 'categories': 635,
 'wasnt': 636,
 'neutral': 637,
 'received': 638,
 'soviet': 639,
 'ultimatum': 640,
 'much': 641,
 'montreals': 642,
 'industry': 643,
 'late': 644,
 'earlytomid': 645,
 'sudouest': 646,
 'borough': 647,
 'home': 648,
 'citys': 649,
 'pascal': 650,
 'write': 651,
 'cycloid': 652,
 'sheriff': 653,
 'erire': 654,
 'county': 655,
 'produce': 656,
 'blowing': 657,
 'closed': 658,
 'lips': 659,
 'trumpets': 660,
 'bright': 661,
 'loud': 662,
 'trombone': 663,
 'roughly': 664,
 'cylindrical': 665,
 'bore': 666,
 'goh': 667,
 'chok': 668,
 'tong': 669,
 'succeed': 670,
 'lee': 671,
 'prime': 672,
 'minister': 673,
 'succeeded': 674,
 'several': 675,
 'sources': 676,
 'nearly': 677,
 'extinct': 678,
 'hairs': 679,
 'per': 680,
 'square': 681,
 'cm': 682,
 'skin': 683,
 'rich': 684,
 'fur': 685,
 'hunted': 686,
 'them': 687,
 'study': 688,
 'ecclesiastical': 689,
 'law': 690,
 'indonesia': 691,
 'worlds': 692,
 'hightest': 693,
 'level': 694,
 'biodiversity': 695,
 'after': 696,
 'cleveland': 697,
 'left': 698,
 'office': 699,
 'us': 700,
 'spanishamerican': 701,
 'den': 702,
 'called': 703,
 'holt': 704,
 'hungary': 705,
 'sole': 706,
 'winner': 707,
 'tune': 708,
 'cello': 709,
 'pegs': 710,
 'these': 711,
 'projections': 712,
 'papillae': 713,
 'blood': 714,
 'supply': 715,
 'newtons': 716,
 'views': 717,
 'consistent': 718,
 'anglicanism': 719,
 'conflict': 720,
 'anglican': 721,
 'orthodoxy': 722,
 'averted': 723,
 'garbage': 724,
 'recycled': 725,
 'transported': 726,
 'thompson': 727,
 'manitoba': 728,
 'mothers': 729,
 'lose': 730,
 'chick': 731,
 'sometimes': 732,
 'attempt': 733,
 'steal': 734,
 'another': 735,
 'james': 736,
 'cook': 737,
 'name': 738,
 'kangooroo': 739,
 'fish': 740,
 'primary': 741,
 'item': 742,
 'diet': 743,
 'supplemented': 744,
 'frogs': 745,
 'crayfish': 746,
 'crabs': 747,
 'older': 748,
 'refer': 749,
 'country': 750,
 'people': 751,
 'consitution': 752,
 'formerly': 753,
 'north': 754,
 'america': 755,
 'retire': 756,
 'same': 757,
 'place': 758,
 'egypt': 759,
 'republic': 760,
 'species': 761,
 'zebras': 762,
 'interbreed': 763,
 'there': 764,
 'monument': 765,
 'niagara': 766,
 'falls': 767,
 'otter': 768,
 'inhabit': 769,
 'africa': 770,
 'start': 771,
 'boxing': 772,
 'lessons': 773,
 'deal': 774,
 'bullies': 775,
 'countries': 776,
 'vi': 777,
 'scotland': 778,
 'unite': 779,
 'england': 780,
 'lewis': 781,
 'use': 782,
 'absolute': 783,
 'case': 784,
 'instead': 785,
 'nominative': 786,
 'indefinite': 787,
 'accusative': 788,
 'game': 789,
 'marn': 790,
 'grook': 791,
 'using': 792,
 'ball': 793,
 'kangaroo': 794,
 'kurnai': 795,
 'reach': 796,
 'breeding': 797,
 'age': 798,
 'shape': 799,
 'black': 800,
 'rossettes': 801,
 'east': 802,
 'circular': 803,
 'significant': 804,
 'nonofficial': 805,
 'parliament': 806,
 'malaysia': 807,
 'abbreviation': 808,
 'violoncello': 809,
 'vietnamese': 810,
 'official': 811,
 'vietnam': 812,
 'buried': 813,
 'pittsburgh': 814,
 'como': 815,
 'italy': 816,
 'definite': 817,
 'article': 818,
 'turkish': 819,
 'meanings': 820,
 'book': 821,
 'defined': 822,
 'finnish': 823,
 'dictionary': 824,
 'contemporary': 825,
 'turtle': 826,
 'popularly': 827,
 'kept': 828,
 'pet': 829,
 'russian': 830,
 'celsius': 831,
 'crater': 832,
 'moon': 833,
 'named': 834,
 'him': 835,
 'anders': 836,
 'celcius': 837,
 'publish': 838,
 'aurora': 839,
 'borealis': 840,
 'results': 841,
 'introduction': 842,
 'alphabet': 843,
 'dramatic': 844,
 'increase': 845,
 'literacy': 846,
 'original': 847,
 'levels': 848,
 'you': 849,
 'meet': 850,
 'someone': 851,
 'attending': 852,
 'slow': 853,
 'metabolism': 854,
 'slide': 855,
 'allowed': 856,
 'churchill': 857,
 'occupation': 858,
 'singapor': 859,
 'janpan': 860,
 'wwii': 861,
 'britains': 862,
 'greatest': 863,
 'defeat': 864,
 'defeated': 865,
 'six': 866,
 'days': 867,
 'generally': 868,
 'woodrow': 869,
 'wilson': 870,
 'leave': 871,
 'practice': 872,
 'government': 873,
 'eels': 874,
 'approximately': 875,
 'parts': 876,
 'disc': 877,
 'speak': 878,
 'worldwide': 879,
 'native': 880,
 'speakers': 881,
 'panda': 882,
 'endangered': 883,
 'vehicles': 884,
 'frequent': 885,
 'isolated': 886,
 'roads': 887,
 'often': 888,
 'fitted': 889,
 'roo': 890,
 'bars': 891,
 'charlesaugustin': 892,
 'de': 893,
 'coulomb': 894,
 'fathers': 895,
 'montpellier': 896,
 'took': 897,
 'academy': 898,
 'religions': 899,
 'outlawed': 900,
 'but': 901,
 'christianity': 902,
 'judaism': 903,
 'we': 904,
 'musicians': 905,
 'play': 906,
 'flautist': 907,
 'flutist': 908,
 'came': 909,
 'xylophone': 910,
 'vibraphone': 911,
 'king': 912,
 'victor': 913,
 'emmanuel': 914,
 'iii': 915,
 'pay': 916,
 'homage': 917,
 'average': 918,
 'next': 919,
 'small': 920,
 'tremor': 921,
 'occur': 922,
 'beneficial': 923,
 'alpha': 924,
 'males': 925,
 'females': 926,
 'forcefully': 927,
 'prevent': 928,
 'wolves': 929,
 'mating': 930,
 'pack': 931,
 'suppport': 932,
 'littler': 933,
 'entries': 934,
 'character': 935,
 'definitions': 936,
 'zhonghua': 937,
 'zihai': 938,
 'contain': 939,
 'protocubist': 940,
 'les': 941,
 'demoiselles': 942,
 'davignon': 943,
 'guernica': 944,
 'portrayal': 945,
 'bombing': 946,
 'spanish': 947,
 'civil': 948,
 'main': 949,
 'groups': 950,
 'those': 951,
 'brazil': 952,
 'remarkably': 953,
 'effective': 954,
 'writer': 955,
 'thinker': 956,
 'sir': 957,
 'thomas': 958,
 'stamford': 959,
 'raffles': 960,
 'india': 961,
 'live': 962,
 'few': 963,
 'mountain': 964,
 'ranges': 965,
 'central': 966,
 'china': 967,
 'drums': 968,
 'sri': 969,
 'lanka': 970,
 'christ': 971,
 'swedish': 972,
 'descendant': 973,
 'norse': 974,
 'color': 975,
 'heritable': 976,
 'caused': 977,
 'recessive': 978,
 'gene': 979,
 'locus': 980,
 'consists': 981,
 'low': 982,
 'barren': 983,
 'plain': 984,
 'covered': 985,
 'singapores': 986,
 'climate': 987,
 'uniform': 988,
 'temperature': 989,
 'high': 990,
 'humidity': 991,
 'abundant': 992,
 'rainfall': 993,
 'makes': 994,
 'san': 995,
 'francisco': 996,
 'topten': 997,
 'american': 998,
 'destinations': 999,
 ...}

In [28]:
def text_to_indices(text, vocab,add_eos=False):

    indices = [
        vocab.get(token,vocab['<UNK>'])
        for token in tokenize(text)
    ]
    if add_eos:
        indices.append(vocab['EOS'])
    return indices

In [29]:
df['Question'][0].split()

['Is',
 'it',
 'true',
 'that',
 'he',
 'sent',
 'in',
 'federal',
 'troops',
 'to',
 'chicago?']

In [32]:
text_to_indices(df['Question'][0],vocab)

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [33]:
df

,Question,Answer
0,Is it true that he sent in federal troops to c...,yes
1,Was Amedeo Avogadro was born in Turin?,yes
2,What happened in the early 20th century?,The koalas of South Australia were largely ext...
3,What are the reasons for hunting wild ducks?,"Meat, eggs, and feathers"
4,Has tusklessness become a rare abnormality?,"No, tusklessness has become a widespread hered..."
...,...,...
195,Did James Monroe attend the College of William...,Yes
196,What did Cleveland die from?,A heart attack
197,Is it true that he became a professor in 1820?,yes
198,When did Watt retire?,In 1800.
199,Has tusklessness become a rare abnormality?,No

In [34]:
df.iloc[0]['Question']

'Is it true that he sent in federal troops to chicago?'

In [36]:
import torch
from torch.utils.data import DataLoader , Dataset

In [37]:
class QADataset(Dataset):

    def __init__(self,df,vocab):
        self.df = df
        self.vocab = vocab

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self,index):

        numerical_question = text_to_indices(self.df.iloc[index]['Question'],self.vocab)
        numerical_answer = text_to_indices(self.df.iloc[index]['Answer'],self.vocab,add_eos=True)

        return torch.tensor(numerical_question) , torch.tensor(numerical_answer)

In [38]:
dataset = QADataset(df,vocab)

In [39]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [40]:
for question , answer in dataloader:
    print(question,answer[0])

tensor([[ 54, 263, 506,  47, 507, 329, 508]]) tensor([15,  2])
tensor([[  4,  23, 800, 975, 976,  42, 977,  74, 378, 443, 978, 979, 980]]) tensor([15,  2])
tensor([[ 21, 134, 152,  23, 576,  28,  47, 577,   4, 578]]) tensor([  5, 579,  47, 580, 117,   4,  10,  47, 581, 582, 342,  23, 583,  28,
         23, 577,   2])
tensor([[ 21,  92, 904, 749, 905, 129, 906, 584]]) tensor([ 47, 584, 585,  47, 907, 304,  47, 908,   2])
tensor([[152,  16,   8,  73, 653,  28, 654, 655, 149, 150]]) tensor([15,  2])
tensor([[312,  92, 660,  98,  47, 661, 662, 580]]) tensor([ 23, 348,  42, 663, 506,  47, 664, 665, 666,   2])
tensor([[122, 123,  23, 918,  10,  21, 546, 141,  23, 919, 920, 921, 922,  10,
         490]]) tensor([2])
tensor([[  21,  153,  836,  831, 1017,  127,   23,  627,   28,  629]]) tensor([1018,  329,  631,  632,    2])
tensor([[  4,  23, 466, 467, 468,  10, 469]]) tensor([15,  2])
tensor([[  4,   5,   6,   7,   8, 470,  47, 284,  10]]) tensor([15,  2])
tensor([[184,  92, 235, 459, 460, 461,  41]]) tensor([462, 463, 131, 464, 304, 465,   2])
tensor([[482, 849, 850, 851, 355, 852,  47, 434]]) tensor([15,  2])
tensor([[  4,  23, 831, 832, 123,  23, 833, 834, 696, 835]]) tensor([15,  2])
tensor([[ 77,  44, 202, 204, 205, 206, 207]]) tensor([208,  23, 209, 210,  28, 211, 212, 213, 214, 215,  74, 216,  23, 217,
         28,  23, 218, 219, 206, 220, 202,  44,  87, 221,  10, 206, 222, 223,
        224, 205, 206, 225, 226,   2])
tensor([[ 77, 255, 110, 402,  16,  23, 403, 404, 405,  23, 364, 406,  10,  23,
         266]]) tensor([140,   2])
tensor([[ 21,   4, 435, 354,  74,  23, 436, 437,  36, 438, 439]]) tensor([440,   2])
tensor([[ 16, 912, 913, 914, 915, 764,  13, 916, 917,  13,  18]]) tensor([15,  2])
tensor([[482,  47, 584, 485, 276, 329, 675, 179, 562, 676]]) tensor([15,  2])
tensor([[ 21, 336, 153, 869, 870, 871, 690, 872,  13, 688]]) tensor([873,   2])
tensor([[152, 153, 836, 837, 838,  70, 391, 123,  23, 839, 840]]) tensor([2])
tensor([[ 31, 855, 660,  23, 242, 660, 856,  10,  23, 203, 434]]) tensor([855, 660,  31,  23, 242, 660, 856,  10,  23, 203, 434,   2])
tensor([[ 16, 194,  47, 195, 196,  28, 197,  10, 198]]) tensor([15,  2])
tensor([[ 184,    4, 1037, 1038]]) tensor([1039,   28,   23, 1040, 1041,  327, 1042,   42,   23, 1043, 1044, 1045,
           2])
tensor([[ 77, 255, 110, 402,  16,   5, 152,   8, 470,  23, 471,  10,  70, 472,
          13, 313,  23, 473, 474, 168,  23, 475, 466, 476, 477]]) tensor([2])
tensor([[711, 712, 703, 713,  98,  21]]) tensor([ 47, 684, 714, 715,   2])
tensor([[312,  34, 235, 261, 677, 678]]) tensor([235, 261,  98, 183, 679, 680, 681, 682,  28, 683,  47, 684, 685,  36,
        117, 116, 686, 687,   2])
tensor([[ 77,  54,  47, 584, 585, 586,  23, 587,  28,  23, 580]]) tensor([ 74, 588,  42, 589, 462,  10,  23, 191,  28,  23, 590,   2])
tensor([[54, 55, 56, 28, 57, 58, 59, 60, 61, 62, 63]]) tensor([15,  2])
tensor([[  4, 972,  47, 973,  28, 504, 974]]) tensor([15,  2])
tensor([[  4, 764,  47, 765,  13, 258, 168, 766, 767, 149, 150]]) tensor([15,  2])
tensor([[ 129, 1012, 1013,   42, 1014, 1015]]) tensor([ 255, 1016,    2])
tensor([[  21,  141,   47, 1019,  782,   13, 1020, 1021, 1022, 1023,    7, 1024,
          123,   60, 1025]]) tensor([1026,   78, 1027,    2])
tensor([[ 21,   4, 443, 804, 805, 180]]) tensor([353,   2])
tensor([[34, 90, 91]]) tensor([15,  2])
tensor([[ 4, 23, 72, 73, 74, 75, 76]]) tensor([15,  2])
tensor([[ 77, 153,  24, 518, 519, 520, 521,  42, 522]]) tensor([ 74,  23, 523,  28,  23, 524, 522, 525, 526, 527, 342, 521,   2])
tensor([[153, 239, 240, 547,  42, 756,  10,  23, 757, 758]]) tensor([15,  2])
tensor([[ 21, 515, 153,  18, 688, 242]]) tensor([689, 690,   2])
tensor([[ 152,   16, 1033, 1034, 1035, 1036]]) tensor([537,   2])
tensor([[ 21, 821, 822,  23, 811, 823, 180]]) tensor([ 23, 824,  28, 825, 823, 822,  23, 811, 823, 180,   2])
tensor([[ 21,   4, 709, 101, 808,  28]]) tensor([809,   2])
tensor([[ 77,   4, 986, 987, 563]]) tensor([ 60, 987,   4, 563,  74, 988, 989,  42, 632, 990, 991,  42, 992, 993,
          2])
tensor([[625,  23, 426,  28, 318, 319]]) tensor([626,   2])
tensor([[141, 245,  42, 246, 247, 248,  23, 249,  28, 250, 251, 252,  36, 183,
         253,  13, 254]]) tensor([15,  2])
tensor([[312, 153, 162, 771, 772, 773]]) tensor([ 13, 774, 329, 775,   2])
tensor([[  4,  55, 292, 168, 101, 293, 294,  28,  23, 295]]) tensor([15,  2])
tensor([[153, 650, 651, 127, 652, 509]]) tensor([50,  2])
tensor([[ 21,   4,  23, 538, 539,  10, 540]]) tensor([203,   2])
tensor([[44, 45, 46, 47, 48, 49]]) tensor([50,  2])
tensor([[ 21,   4, 101, 261, 702, 703]]) tensor([704,   2])
tensor([[184,   4,  23, 478,  28, 479, 480]]) tensor([ 23, 478,  28, 479, 480,   4,  10,  23, 481, 468,   2])
tensor([[ 16, 280, 281, 282]]) tensor([ 15,   8,  16, 283,   2])
tensor([[ 21, 821, 822,  23, 811, 823, 180]]) tensor([ 23, 824,  28, 825, 823,   2])
tensor([[ 21,  92, 364, 411, 320, 412,  42, 199, 413,  98,  10, 414]]) tensor([171,  34, 415,   2])
tensor([[312, 636, 263, 637, 208, 266, 267, 388]]) tensor([  5, 638,  47, 639, 640,   2])
tensor([[21, 22, 10, 64, 65, 66]]) tensor([67, 68, 69, 70, 61, 71,  2])
tensor([[  4,  23, 113, 882, 101, 883, 761]]) tensor([15,  2])
tensor([[152, 153,   8, 547]]) tensor([2])
tensor([[ 129,   16,   47,  592,   28,   23, 1008, 1009,   28,  902]]) tensor([306,   2])
tensor([[  4, 104, 105, 106]]) tensor([15,  2])
tensor([[ 77,  78,  16, 239, 240,  47, 284, 168,  23, 285,  28, 286]]) tensor([239, 240,  16,  47, 284, 168,  23, 285,  28, 286,  36, 287, 110,   2])
tensor([[153, 430, 431, 432, 168,  23, 433, 434,  10, 149, 150]]) tensor([15,  2])
tensor([[ 21,   4,  47, 348, 349,  28]]) tensor([350, 351,   2])
tensor([[ 21,   4,  23, 298, 299, 300, 301, 302, 303, 304, 301, 305]]) tensor([ 23, 258,   2])
tensor([[  4, 335, 336, 101, 337]]) tensor([15,  2])
tensor([[ 31, 716, 200, 717, 718, 329, 719]]) tensor([ 50,  47, 720, 520, 716, 200, 717,  42, 721, 722,  16, 723,   2])
tensor([[ 16, 441, 442, 443,  28,  23, 444,  28, 445]]) tensor([15,  2])
tensor([[ 16, 258,  19,  10,  23, 218, 362]]) tensor([50,  2])
tensor([[184,  16, 641,  28, 642, 643, 208,  23, 644,  25,  42, 645,  25,  26]]) tensor([ 23, 646, 647,  16, 648,  13, 641,  28,  23, 649, 643, 208,  23, 644,
         25,  42, 645,  25,  26,   2])
tensor([[ 21,  34,  23,  99, 949, 950,  28, 422,  80]]) tensor([951,  28, 952,  42, 951,  28,  23, 504, 266,   2])
tensor([[ 21,  44, 255, 494, 820]]) tensor([21,  2])
tensor([[ 77, 255, 761,  28,   6, 874,  34, 764]]) tensor([875, 761,   2])
tensor([[ 184,    4,   23, 1031,  175]]) tensor([ 168,   23,  455,   28,   23, 1032,    2])
tensor([[ 16, 240, 238,  47, 560,  10]]) tensor([15,  2])
tensor([[ 16, 870,  47, 953, 954, 955,  42, 956]]) tensor([15,  2])
tensor([[312, 857, 703,  23, 858,  28, 859,  74, 860, 208, 861, 862, 863, 864]]) tensor([ 23, 282,  31, 865,  10, 866, 867,   2])
tensor([[ 21,   4,  23, 627, 628,  28, 629, 630, 123]]) tensor([631, 632,   2])
tensor([[ 21,   4, 354,  13, 708,  47, 709]]) tensor([710,  34, 354,  13, 708,  47, 709,   2])
tensor([[152,  31,  23, 452, 453,  10, 318, 319, 349]]) tensor([454,  23, 455,  28,  23,  25,  42,  24,  25, 356,   2])
tensor([[748, 283, 676, 354,  23, 738, 181,  13, 749,  13,  21]]) tensor([180, 750,  42, 751,   2])
tensor([[153,  23, 269, 270,  23, 271, 272]]) tensor([50,  2])
tensor([[  21,  994,  995,  996,  419,   23,  997,  754,  998,  999,   36, 1000,
           42, 1001]]) tensor([ 995,  996,   44,   47,  564, 1002, 1003,   42,   47, 1004, 1005, 1006,
          10,   23, 1007,  576,    2])
tensor([[184,  34,  23, 378, 274, 113, 379]]) tensor([380,  42, 381, 382,   2])
tensor([[152, 153, 667, 668, 669, 670, 671, 178, 672, 673]]) tensor([ 10, 667, 668, 669, 674, 671, 178, 672, 673,   2])
tensor([[ 153,  306,   98,  567, 1010, 1011]]) tensor([15,  2])
tensor([[ 21,   4, 601, 602,  28, 344, 466, 603, 604]]) tensor([605, 344, 606,   2])
tensor([[ 34, 419,  70, 364, 365, 358,  23, 940, 941, 942, 943,  42, 944,  70,
         945,  28,  23, 125, 946,  28, 944, 208,  23, 947, 948, 267]]) tensor([15,  2])
tensor([[ 21, 799,  34,  47, 521, 800, 801,  10, 802, 770]]) tensor([803,   2])
tensor([[ 21, 981,  28,  47, 982, 983, 984, 985, 329, 465]]) tensor([641,  28,  23, 750,   2])
tensor([[312,  92, 548,  98,  47, 549, 550]]) tensor([ 23,  99, 551,  28,  23, 552, 553,  34, 554, 555, 556,  42,  23, 552,
        557,  34, 558, 559,   2])
tensor([[ 21,   4,  23, 426,  28,  23, 427,  28, 428]]) tensor([429, 426,   4,   2])
tensor([[ 21, 776, 153, 736, 777,  28, 778, 779]]) tensor([736, 777,  28, 778, 218, 778,  42, 780,   2])
tensor([[36, 77, 78, 44, 23, 79, 28, 80, 81, 82, 28, 83, 84, 47, 85, 86]]) tensor([23, 79, 28, 80, 81, 82, 28, 83, 44, 84, 47, 85, 86, 87, 88, 89, 10,  2])
tensor([[ 16, 736, 737,  23, 242,  13, 447,  23, 738, 739]]) tensor([15,  2])
tensor([[ 92, 407, 408, 409,  10, 410]]) tensor([15,  2])
tensor([[ 21, 899,  44, 759, 900]]) tensor([158, 901, 902, 457,  42, 903,   2])
tensor([[619, 193,  23, 620, 621, 200, 622,  31, 171,  75, 178,  47, 623, 624]]) tensor([15,  2])
tensor([[ 153,  736,  430, 1052,   23, 1053,   28, 1054,   42, 1055]]) tensor([15,  2])
tensor([[ 21, 595,   7,  28,  23, 596, 597,  10,  23, 598]]) tensor([ 23, 521, 599, 600,   2])
tensor([[153, 306, 307, 308,  23, 309,  28, 310]]) tensor([ 15, 306, 307, 311,  23, 309,  28, 310,   2])
tensor([[ 92, 323, 307, 324,  36, 325, 326, 327,  10, 328, 329, 330, 331,  13,
         332, 333, 334]]) tensor([323, 307, 324,  36, 325, 326, 327,  10, 328, 329, 330, 331,  13, 332,
        333, 334,   2])
tensor([[312, 153, 125,  12, 313, 314]]) tensor([315,   5,  16, 316,   2])
tensor([[ 16, 441, 442,  23, 706, 707,  28,  23, 573, 574,  10, 473]]) tensor([50,  2])
tensor([[ 54,  23, 113, 768, 769,  29, 770]]) tensor([50,  2])
tensor([[ 54,  23, 422, 180,  98,  60, 423,  10,  23, 424, 180]]) tensor([ 15, 422,   4, 425, 193, 424,   2])
tensor([[312, 153, 571, 572,  23, 573, 574,  10, 473]]) tensor([ 16,  23, 575,  28, 445,   2])
tensor([[ 98, 364, 261, 740, 178,  23, 741, 742,  10, 461, 743, 744,  74, 745,
         746,  42, 747]]) tensor([15,  2])
tensor([[ 21, 134, 152, 729, 730,  47, 731]]) tensor([171, 732, 733,  13, 734, 735, 731,   2])
tensor([[  4,   5, 563,  74, 564, 565, 297,  99, 566,  28, 567, 568, 569,  42,
         101, 570, 191]]) tensor([15,  2])
tensor([[395, 541,  42, 542, 543, 544,  13, 545, 291, 178, 202,  10,  21, 546]]) tensor([2])
tensor([[  4,  23, 173,  81,  10, 174, 175,  10, 176, 177, 178,  47, 179, 180,
          74, 158, 181, 182]]) tensor([ 23, 173,  81,  10, 174,   4,  10, 176, 177, 178,  47, 179, 180,  74,
        183, 181, 182,   2])
tensor([[ 21,  92, 158, 459,  42, 379, 561]]) tensor([562,   2])
tensor([[ 54,  47, 338, 339,  98, 340, 341, 342,  47, 343]]) tensor([50,  2])
tensor([[  4, 764,  47, 817, 818,  10, 819, 180]]) tensor([50,  2])
tensor([[ 16, 344, 101, 345,  28,  23, 346, 347]]) tensor([15,  2])
tensor([[129, 392, 393,  23, 394,  42, 197,  28, 106]]) tensor([395, 396,   2])
tensor([[ 21, 317,  54, 318, 319,  98]]) tensor([318, 319, 320, 321,  42, 322, 320, 321,   2])
tensor([[ 92, 158,  39, 159]]) tensor([50,  2])
tensor([[ 21,   4,  23, 513, 496, 497,  10, 514]]) tensor([515, 516, 517,   2])
tensor([[  21,    4,   23,  199, 1028,  761,   28, 1029]]) tensor([1030, 1029,    2])
tensor([[312,   4, 194, 456,  13, 457]]) tensor([194,   4,  23, 458, 180,  28, 457,   2])
tensor([[  4, 810,  23, 811, 438, 180,  28, 812]]) tensor([15,  2])
tensor([[117, 909, 242,  23, 910, 304,  23, 911]]) tensor([ 23, 910,   2])
tensor([[ 34, 111, 112]]) tensor([15,  2])
tensor([[ 54, 691,  98,  23, 692, 693, 694,  28, 695]]) tensor([50,  2])
tensor([[482, 459, 616, 255, 110,  13, 796, 797, 798]]) tensor([15,  2])
tensor([[  4,   5, 494,  13, 495,  23, 496, 497,  13, 498,  23, 499,  28,  47,
         500, 501]]) tensor([15,  2])
tensor([[  4, 443,  28,  23, 876,  28,  47, 577, 703,  47, 877]]) tensor([50,  2])
tensor([[117, 118,  74, 119, 120,   4, 121, 122, 123, 101, 124, 125, 126, 127,
          47, 128, 129,  16, 130, 131,  47, 132]]) tensor([132, 133,   2])
tensor([[ 77, 482,  47, 483, 484, 485, 486]]) tensor([ 47, 483, 484, 482, 485, 486,  74, 487,  60, 488,  42, 489, 462, 143,
          2])
tensor([[ 21,  34, 884,   7, 885, 886, 887, 888, 889, 329]]) tensor([890, 891,   2])
tensor([[ 77, 255, 751, 878, 819, 879]]) tensor([764,  34, 664, 735, 626, 880, 881, 879,   2])
tensor([[ 21,   4, 145, 146]]) tensor([101, 147,  10, 148, 149, 150, 151,   2])
tensor([[ 87, 152,  44, 759,  84,  47, 760]]) tensor([536,   2])
tensor([[ 10, 607, 608,   4, 609, 610, 354]]) tensor([15,  2])
tensor([[184,  16,  23, 185, 186,  28,  23, 187, 188,  10, 189,  13,  23, 190,
         191]]) tensor([  5,  16, 192, 193,  23, 190, 191,   2])
tensor([[ 21, 446, 153,   8, 447,  10,  70, 448]]) tensor([449,  28, 450,  42, 451,  28, 109,   2])
tensor([[ 47, 227, 228, 229,  23, 230, 231,  44,  21]]) tensor([  5,  44, 232,  36, 107, 123,  47, 233,  28, 234, 235,  42, 236,   2])
tensor([[ 21,   4,  23, 199, 200, 201,  10, 202]]) tensor([203,   2])
tensor([[ 54, 263, 507, 705]]) tensor([15,  2])
tensor([[ 152,  153, 1046,  756]]) tensor([10,  2])
tensor([[44, 45, 46, 47, 48, 49]]) tensor([50, 45, 44, 46, 47, 51, 52, 53,  2])
tensor([[482, 633, 485, 634, 131,  99, 360, 635]]) tensor([15,  2])
tensor([[152, 153, 154, 155,  23, 156, 157]]) tensor([2])
tensor([[  8, 389,  47, 390,  28,  21]]) tensor([391,   2])
tensor([[ 92, 113, 114, 115, 116]]) tensor([15,  2])
tensor([[312,   4,   5, 923,  36, 924, 925,  42, 926,  13, 927, 928, 139, 929,
         193, 930]]) tensor([ 47, 931, 482, 378, 932, 443, 933, 680, 546,   2])
tensor([[184,  92, 113, 114, 962]]) tensor([ 47, 963, 964, 965,  10, 966, 967,   2])
tensor([[ 21,   4, 288]]) tensor([289, 290, 105, 291,   2])
tensor([[184,  16, 240,  19]]) tensor([815, 816,   2])
tensor([[312,  54, 781, 782, 783, 784, 785,  28, 786]]) tensor([315,   5,   4, 307, 354,  36,  23, 787, 788,   2])
tensor([[ 77, 255, 110, 696, 697, 698, 699, 153,  23, 700, 572,  23, 701, 267]]) tensor([443, 546,   2])
tensor([[  4,   5, 648,  13,  23, 806,  28, 807]]) tensor([15,  2])
tensor([[153, 615, 616, 617,  28,  23, 283, 618,  10]]) tensor([50,  2])
tensor([[ 16, 240, 397,  10, 398, 399]]) tensor([15,  2])
tensor([[724,   4,  21]]) tensor([724,   4, 601, 725, 304, 726,  13, 727, 728,   2])
tensor([[ 21,   4,  23, 237, 238,  74, 239, 240, 241, 178]]) tensor([ 23, 242, 243, 244,   2])
tensor([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]) tensor([15,  2])
tensor([[ 34, 261, 262]]) tensor([50,  2])
tensor([[ 77, 255,  58, 934,  36, 935, 936,  54,  23, 937, 938, 939]]) tensor([ 58, 934,   2])
tensor([[ 34, 611,  39, 612, 613, 614,  39]]) tensor([15,  2])
tensor([[ 736, 1046, 1047,  242,  419,   77,  255,  751,   10, 1048, 1049, 1050,
           28, 1051]]) tensor([2])
tensor([[  4,  10,  23, 273, 274, 275, 275, 276,  74, 277, 278, 279]]) tensor([15,  2])
tensor([[ 16,  23, 789,  28, 790, 791, 276, 792,  47, 793, 238, 193, 794,  74,
          23, 795, 751]]) tensor([15,  2])
tensor([[ 77, 153, 160, 161,  13, 162, 163, 164, 165, 166,  13, 167, 168,  23,
         169, 170]]) tensor([171, 172,   2])
tensor([[ 92,  27,  98,  47, 853, 854]]) tensor([15,  2])
tensor([[ 54,  23, 296,  98,  99, 297]]) tensor([ 15,  23, 296,  44,  99, 297,   2])
tensor([[152,   4,  23, 533, 534, 535]]) tensor([520, 536,  42, 537,   2])
tensor([[ 77, 255, 256, 153, 257, 258,  98]]) tensor([257, 258, 259, 260, 256,   2])
tensor([[ 92,  23,  93,  10,  23,  94,  95,  96,  97,  98,  99, 100,  42, 101,
         102, 103]]) tensor([ 15,  23,  93,  10,  23,  94,  95,  96,  97,  98,  99, 100,  42, 101,
        102, 103,   2])
tensor([[ 92,  70, 358, 359,  47, 360,  75, 361,  10,  23, 218, 362, 184, 363,
           4, 364, 365,  36,  23, 366, 367,  28, 368, 107, 369,   8, 370,  36,
          23, 371, 372, 373, 374, 375, 376, 342, 260, 377]]) tensor([15,  2])
tensor([[ 21,  16, 443,  28,  23, 841,  28,  23, 842,  28,  23, 149, 819, 843]]) tensor([764,  16,  47, 844, 845,  10, 846, 193,  60, 847, 471, 266, 848,   2])
tensor([[259,  23, 968,  84, 354,  10, 969, 970,  87, 509, 971]]) tensor([15,  2])
tensor([[ 77,  54,  47, 348, 656, 580]]) tensor([ 74, 657, 562, 355, 658, 659,   2])
tensor([[ 16, 528, 529,  23, 530,  72,  28,  23, 218, 362]]) tensor([15,  2])
tensor([[21, 22, 10, 23, 24, 25, 26]]) tensor([23, 27, 28, 29, 30, 31, 32, 33,  2])
tensor([[16, 17, 18, 16, 19, 10, 20]]) tensor([15,  2])
tensor([[153, 263, 264, 265, 208, 266, 267, 268]]) tensor([15,  2])
tensor([[129, 153, 957, 958, 959, 960, 624,  36]]) tensor([282, 802, 961, 412,   2])
tensor([[ 21, 153, 697, 547, 193]]) tensor([  47, 1056,  115,    2])
tensor([[152,  16, 352, 353, 354]]) tensor([352, 353,  16,  23, 180, 354,  10,  23,  25, 355,  25, 356, 357,   2])
tensor([[21, 34, 23, 35, 36, 37, 38, 39]]) tensor([40, 41, 42, 43,  2])
tensor([[ 21,   4,  23, 266, 426,  28, 531, 532]]) tensor([2])
tensor([[509,  16, 510, 511,  74, 512]]) tensor([15,  2])
tensor([[  4, 240, 813,  10,  23, 427,  28, 814]]) tensor([50,  2])
tensor([[ 16, 240, 397,  10, 398, 399]]) tensor([15,  2])
tensor([[ 21,   4,  23, 107, 108,  36, 109]]) tensor([110,   2])
tensor([[748, 283, 676, 354,  23, 738, 181,  13, 749,  13,  21]]) tensor([180, 750,  42, 751,   2])
tensor([[ 21, 383,  10, 384]]) tensor([ 23, 242, 385, 386, 387,  10, 316, 388,   2])
tensor([[135, 441, 442,  16, 502, 503,  77, 504, 505,   8,  98,  84]]) tensor([2])
tensor([[738,  47, 826, 827, 828, 178,  47, 829]]) tensor([830, 379,   2])
tensor([[ 21, 134, 135,  47, 136,   4, 137]]) tensor([135,  47, 138,   4, 137,  23, 139, 140, 141, 142,  13,  47, 143, 144,
          2])
tensor([[ 16, 591, 162,  47, 592,  28,  23, 593, 594]]) tensor([15,  2])
tensor([[ 92,  23, 179, 761,  28, 762, 763]]) tensor([50,  2])
tensor([[ 21,  16,  23, 752, 347, 753, 703]]) tensor([282, 754, 755, 347,   2])
tensor([[21, 22, 10, 13]]) tensor([892, 893, 894, 555,  70, 895, 472,  10, 896,  42, 897, 602,  10,  23,
        624,  28,  23, 898,  28,  23, 427,   2])
tensor([[  4, 416, 417, 418, 419, 420, 421]]) tensor([15,  2])
tensor([[  4, 490, 491, 342, 492,  10, 493]]) tensor([15,  2])
tensor([[ 77, 482,  47, 483, 484, 485, 486]]) tensor([ 47, 483, 484, 482, 868, 485, 486,  74, 487,  60, 488,  42, 489, 462,
        143,   2])
tensor([[ 16, 306, 400,  47, 401]]) tensor([50,  2])

In [35]:
# X = nn.Embedding(544,embedding_dim=50)
# Y = nn.RNN(50,64,batch_first = True)
# Z = nn.Linear(64,544)

# # step 1 data

# a = dataset[0][0].reshape(1,3)
# print(f"Shape of a: {a.shape}")
# b = X(a) # 50 dim
# print(f"Shape of b: {b.shape}")
# c , d = Y(b) # RNN
# print(f"Shape of c :{c.shape} \nShape of d : {d.shape}")

# e = Z(d.squeeze(0))
# print(f"Shape of e: {e.shape}")

In [42]:
import torch.nn as nn

In [60]:
a = torch.tensor(text_to_indices(df['Question'][0],vocab))
torch.ones(len(a),1,dtype=torch.long).shape

torch.Size([11, 1])

In [64]:
df

,Question,Answer
0,Is it true that he sent in federal troops to c...,yes
1,Was Amedeo Avogadro was born in Turin?,yes
2,What happened in the early 20th century?,The koalas of South Australia were largely ext...
3,What are the reasons for hunting wild ducks?,"Meat, eggs, and feathers"
4,Has tusklessness become a rare abnormality?,"No, tusklessness has become a widespread hered..."
...,...,...
195,Did James Monroe attend the College of William...,Yes
196,What did Cleveland die from?,A heart attack
197,Is it true that he became a professor in 1820?,yes
198,When did Watt retire?,In 1800.
199,Has tusklessness become a rare abnormality?,No

In [71]:
torch.tensor(text_to_indices(df['Answer'][2],vocab))

tensor([23, 27, 28, 29, 30, 31, 32, 33])

In [87]:
# Model Building 
# Simple RNN

class Seq2SeqRNN(nn.Module):
    def __init__(self,vocab_size,embed_dim=50,hidden_dim = 64):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,embed_dim)
        self.encoder = nn.RNN(embed_dim,hidden_dim,batch_first=True)
        self.decoder = nn.RNN(embed_dim,hidden_dim,batch_first=True)
        self.fc = nn.Linear(hidden_dim,vocab_size)

    def forward(self,question,answer=None,max_len=10):

        # Encoder
        embedded_q = self.embedding(question)
        _ , hidden = self.encoder(embedded_q)

        # Decoder - <SOS> token
        batch_size = question.size(0)
        decoder_input = torch.ones(batch_size , 1 , dtype=torch.long)

        outputs = []
        seq_len = answer.size(1) if answer is not None else max_len

        for i in range(seq_len):
            embedded_d = self.embedding(decoder_input)
            out , hidden = self.decoder(embedded_d,hidden)
            prediction = self.fc(out.squeeze(1))  # [1,vocab_size]
            outputs.append(prediction)

            if answer is not None:
                decoder_input = answer[:,i].unsqueeze(1)  # teacher forcing
            else:
                decoder_input = prediction.argmax(dim=1).unsqueeze(1)
        return torch.stack(outputs,dim=1)   # [1,seq_len , vocab_size]

In [88]:
learning_rate = 0.001
epochs = 100

In [89]:
model = Seq2SeqRNN(len(vocab))

In [90]:
# loss , optimizer 

criterion = nn.CrossEntropyLoss(ignore_index=0)
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [91]:
# for q,a in dataloader:
#     print(a)
#     print("1d :-",a.flatten())
#     print("scaler vaule :-",a.flatten()[0])
#     print("unsqueeze(0)  :-",a.flatten()[0].unsqueeze(0) )
#     break

In [92]:
# Training Loop


for epoch in range(epochs):
    total_loss =0 

    for question , answer in dataloader:
        if answer.numel() == 0:
            continue
        optimizer.zero_grad()

        output = model(question,answer)
        output_flat = output.view(-1,len(vocab)) # [1,seq_len,vocab_size]
        target_flat = answer.view(-1)
    
        loss = criterion(output_flat , target_flat)
        loss.backward()

        optimizer.step()

        total_loss += loss.item()
    print(f"Epoch : {epoch+1} , Loss : {total_loss:.4f}")

Epoch : 1 , Loss : 914.4972
Epoch : 2 , Loss : 653.8432
Epoch : 3 , Loss : 591.7310
Epoch : 4 , Loss : 530.3949
Epoch : 5 , Loss : 475.7310
Epoch : 6 , Loss : 425.7673
Epoch : 7 , Loss : 380.6088
Epoch : 8 , Loss : 339.6999
Epoch : 9 , Loss : 299.7884
Epoch : 10 , Loss : 261.6678
Epoch : 11 , Loss : 226.1390
Epoch : 12 , Loss : 194.1989
Epoch : 13 , Loss : 165.3166
Epoch : 14 , Loss : 140.2509
Epoch : 15 , Loss : 119.5130
Epoch : 16 , Loss : 100.7690
Epoch : 17 , Loss : 85.0672
Epoch : 18 , Loss : 71.7296
Epoch : 19 , Loss : 61.0800
Epoch : 20 , Loss : 51.9520
Epoch : 21 , Loss : 44.1547
Epoch : 22 , Loss : 37.4845
Epoch : 23 , Loss : 32.3079
Epoch : 24 , Loss : 28.1208
Epoch : 25 , Loss : 24.1587
Epoch : 26 , Loss : 20.6474
Epoch : 27 , Loss : 17.9212
Epoch : 28 , Loss : 15.4740
Epoch : 29 , Loss : 13.7958
Epoch : 30 , Loss : 11.9280
Epoch : 31 , Loss : 10.5868
Epoch : 32 , Loss : 9.3050
Epoch : 33 , Loss : 8.5918
Epoch : 34 , Loss : 7.7899
Epoch : 35 , Loss : 7.1410
Epoch : 36 , Loss : 6.0262
Epoch : 37 , Loss : 5.2351
Epoch : 38 , Loss : 4.6399
Epoch : 39 , Loss : 4.0392
Epoch : 40 , Loss : 3.7616
Epoch : 41 , Loss : 3.4462
Epoch : 42 , Loss : 3.1226
Epoch : 43 , Loss : 2.9667
Epoch : 44 , Loss : 2.7001
Epoch : 45 , Loss : 2.4360
Epoch : 46 , Loss : 2.3633
Epoch : 47 , Loss : 2.1218
Epoch : 48 , Loss : 2.0067
Epoch : 49 , Loss : 1.9095
Epoch : 50 , Loss : 1.7759
Epoch : 51 , Loss : 1.7020
Epoch : 52 , Loss : 1.6404
Epoch : 53 , Loss : 1.5581
Epoch : 54 , Loss : 1.4339
Epoch : 55 , Loss : 1.3416
Epoch : 56 , Loss : 1.3656
Epoch : 57 , Loss : 1.2909
Epoch : 58 , Loss : 1.2190
Epoch : 59 , Loss : 1.2047
Epoch : 60 , Loss : 1.1623
Epoch : 61 , Loss : 1.1001
Epoch : 62 , Loss : 1.0583
Epoch : 63 , Loss : 1.0512
Epoch : 64 , Loss : 1.0323
Epoch : 65 , Loss : 1.0041
Epoch : 66 , Loss : 0.9934
Epoch : 67 , Loss : 0.9229
Epoch : 68 , Loss : 0.9212
Epoch : 69 , Loss : 0.9479
Epoch : 70 , Loss : 34.6025
Epoch : 71 , Loss : 12.5347
Epoch : 72 , Loss : 2.8557
Epoch : 73 , Loss : 1.5819
Epoch : 74 , Loss : 1.3583
Epoch : 75 , Loss : 1.2660
Epoch : 76 , Loss : 1.1620
Epoch : 77 , Loss : 1.1333
Epoch : 78 , Loss : 1.0451
Epoch : 79 , Loss : 1.0461
Epoch : 80 , Loss : 1.0308
Epoch : 81 , Loss : 0.9877
Epoch : 82 , Loss : 1.0111
Epoch : 83 , Loss : 0.9513
Epoch : 84 , Loss : 0.9267
Epoch : 85 , Loss : 0.9674
Epoch : 86 , Loss : 0.9335
Epoch : 87 , Loss : 0.8984
Epoch : 88 , Loss : 0.8862
Epoch : 89 , Loss : 0.8965
Epoch : 90 , Loss : 0.8801
Epoch : 91 , Loss : 0.8027
Epoch : 92 , Loss : 0.8744
Epoch : 93 , Loss : 0.8592
Epoch : 94 , Loss : 0.8383
Epoch : 95 , Loss : 0.8593
Epoch : 96 , Loss : 0.8083
Epoch : 97 , Loss : 0.8103
Epoch : 98 , Loss : 0.7283
Epoch : 99 , Loss : 0.7351
Epoch : 100 , Loss : 0.8109

In [46]:
Q_1 = model(torch.tensor(text_to_indices(df['Question'][0],vocab)).unsqueeze(0))
prob = torch.nn.functional.softmax(Q_1,dim=1)
torch.max(prob,dim=1)

torch.return_types.max(
values=tensor([0.9999], grad_fn=<MaxBackward0>),
indices=tensor([10]))

In [47]:
list(vocab)[5]

'is'

In [124]:
def predict(model,question,vocab,threshold=0.5,max_len=10):
    model.eval()
    index_to_word = {idx:word for word,idx in vocab.items()}

    with torch.no_grad():
        numberical_question = text_to_indices(question,vocab)
        
        # shape [1,seq_len]
        question_tensor = torch.tensor(numberical_question).unsqueeze(0)

        output = model(question_tensor,answer=None,max_len=max_len)

        # probabilities
        probs = torch.nn.functional.softmax(output,dim=2)
        value , index = torch.max(probs,dim=2)
        # print(f"Value :- {value},Index :- {index}")

        # answer in squance
        answer_words = []
        for i in range(index.size(1)):
            idx = index[0, i].item()
            confidence = value[0 , i].item()

            if idx == vocab.get('<EOS>',-1) or confidence < threshold:
                break

            answer_words.append(index_to_word.get(idx,'<UNK>'))
        
        answer = " ".join(answer_words)
        return f"Answer :- {answer}"

In [125]:
df

,Question,Answer
0,Is it true that he sent in federal troops to chicago?,yes
1,Was Amedeo Avogadro was born in Turin?,yes
2,What happened in the early 20th century?,The koalas of South Australia were largely exterminated.
3,What are the reasons for hunting wild ducks?,"Meat, eggs, and feathers"
4,Has tusklessness become a rare abnormality?,"No, tusklessness has become a widespread hereditary trait."
...,...,...
195,Did James Monroe attend the College of William and Mary?,Yes
196,What did Cleveland die from?,A heart attack
197,Is it true that he became a professor in 1820?,yes
198,When did Watt retire?,In 1800.
199,Has tusklessness become a rare abnormality?,No

In [126]:
pd.set_option('display.max_colwidth', None)

In [131]:
def question_generate(dataframe , index=0):
    text = dataframe['Question'][index] 
    return text,df.iloc[[index]]

text , Q_A = question_generate(df,50)
print(text)
Q_A

Where are the only surviving giant tortoises?

,Question,Answer
50,Where are the only surviving giant tortoises?,Seychelles and Gal�pagos Islands

In [132]:
predict(model,text,vocab,threshold=0.5)

'Answer :- seychelles and gal�pagos islands EOS is'